vmware-samples/vcenter-event-broker-appliance

examples/powercli/tagging/README.md
examples/python/tagging/README.MD

Python tagging example, which is also used in the getting started
guide, did not have a README. This fix makes it easier for users to
directly deploy the Python example with instructions located in the
functions folder.
Also fixes a typo in the PowerCLI tagging function.

Add README to Python tagging example

---

files/kubeconfig.yml
files/setup.sh
files/tinywww-debug.yml
files/tinywww.yml
getting-started.md
photon-dev.json
photon-version.json
photon.json
scripts/photon-containers.sh
scripts/photon-docker.sh
scripts/photon-openfaas.sh

* Changed to the latest k8s v1.14.9 via Kubeadm configuration file as the default version shipped w/PhotonOS 3.0 is still v1.14.6 which may not include all latest CVEs
* Pre-download all required Docker Containers, so internet connectivity is not required for initial VEBA setup
* Update ImagePullPolicy from Always to IfNotPresent which is required or k8s deployment spec will fail as it tries to pull Docker Container even though its already present
* Minor doc/typo fixes

No Internet Required + k8s v1.14.9

---

examples/powercli/hostmaint-alarms/README.md
examples/powercli/hostmaint-alarms/handler/script.ps1
examples/powercli/hostmaint-alarms/stack.yml
examples/powercli/hostmaint-alarms/template/powercli/Dockerfile
examples/powercli/hostmaint-alarms/template/powercli/function/script.ps1
examples/powercli/hostmaint-alarms/template/powercli/template.yml
examples/powercli/hostmaint-alarms/vcconfig.json

This example disables alarms when a host is put in maintenance and re-enables alarms when it exits maintenance.
Signed-off-by: Doug Taliaferro <dougt42@gmail.com>

New example for host maintenance

---

examples/powercli/hostmaint-alarms/README.md
examples/powercli/hostmaint-alarms/stack.yml
examples/powercli/hwchange-slack/README.md
examples/powercli/hwchange-slack/stack.yml
examples/powercli/tagging/stack.yml
examples/python/tagging/README.MD
examples/python/tagging/stack.yml

The default provider name in stack.yml is 'faas', but the function fails to deploy with error "['openfaas'] is the only valid "provider.name" for the OpenFaaS CLI, but you gave: faas". Changing the default provider name to 'openfaas' fixes the problem.
The readme has a typo calling the command 'faas' when the command needs to be 'faas-cli'.
Changed the default provider gateway to a clearer placeholder - deploying VEBA out of the box requires HTTPS URL, and is not running on port 8080.

Fixes to documentation and sample config files for openfaas

---

files/setup.sh
manual/photon.xml.template

PR fixes #30 
Allows to add NTP server(s).
- Checked that the servers entered in the ova setup have been successfully configured as _SystemNTPServers_

Add ntp settings to ova

---

files/setup.sh
manual/photon-dev.xml.template
manual/photon.xml.template
photon-dev.json

Fixes #40 
Provides proxy settings to enable the provisioning of VEBA in environments that allows Internet connection through a proxy only. It is also necessary for functions that require an outgoing connection in such environments.
- validation that the provision of VEBA behind a proxy is successful

Add proxy settings to ova

---

getting-started.md
scripts/photon-openfaas.sh

The docs and /etc/issue of the VM (visible on the console) talk about going to [IP] to see the OpenFaaS UI, but actually it's the hostname that's needed due to the following IngressRoute, where fqdn=hostname:
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
labels:
app: openfaas
name: ingressroute-gateway
namespace: openfaas
spec:
virtualhost:
fqdn: xxx
tls:
secretName: openfaas-gw-tls
minimumProtocolVersion: "1.2"
routes:
- match: /status
prefixRewrite: /status
services:
- name: tinywww
port: 8100
- match: /bootstrap
prefixRewrite: /bootstrap
services:
- name: tinywww
port: 8100
- match: /
services:
- name: gateway
port: 8080
```

replace references of [IP] to [hostname]

---

vmware-event-router/cmd/main.go
vmware-event-router/internal/metrics/server.go

Fix a bug where http server would err but `errGrp.Wait()` waits for **all** Goroutines to finish.

Use ErrorGroup Context to return on first error

---

examples/python/esx-mtu-fixer/README.md
examples/python/tagging/README.MD

Examples run by users should always be run from `master` instead of `development` (default).

Add branch information to Python examples

---

vmware-event-router/Dockerfile
vmware-event-router/Makefile

- Use stricter linting during Docker build/release
- For local testing linting and clean Git dir is not enforced though

Stricter linting on VMware Event Router

---

vmware-event-router/cmd/main.go
vmware-event-router/internal/metrics/server.go
vmware-event-router/internal/processor/aws_event_bridge.go
vmware-event-router/internal/processor/openfaas.go
vmware-event-router/internal/stream/vcenter.go

Fixes linter errors regression introduced in #58
Closes: #60 
Tested via:
```bash
make
[...]
Step 24/24 : ENTRYPOINT ["./vmware-event-router"]
---> Using cache
---> 5c4aa02006a4
Successfully built 5c4aa02006a4
Successfully tagged vmware/veba-event-router:e54fee2
```
Tested the new build successfully against OpenFaaS and AWS EventBridge
with a VmPoweredOffEvent.

Fix linter errors

---

vmware-event-router/cmd/main.go
vmware-event-router/internal/color/color.go
vmware-event-router/internal/metrics/server.go
vmware-event-router/internal/processor/aws_event_bridge.go
vmware-event-router/internal/processor/openfaas.go

Add support for colorized log output for better readability/troubleshooting.

Add support for colorized log output

---

examples/powercli/hostmaint-alarms/README.md
examples/powercli/hostmaint-alarms/handler/script.ps1
examples/powercli/hostmaint-alarms/stack.yml

@kremerpatrick found the initial v0.3 sample did not properly process the MoRef IDs for ESXi host, this PR fixes that sample. Patrick has also validated the function changes in his own environment to ensure things are working and the updated docker container has also been pushed. 

Fix Host MoRef processing for PCLI Host Maintenance Function

---

scripts/photon-settings.sh

This is to resolve https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/65 
Validation:
- Deployed tools.conf configuration and ensure eth0 is listed first and then followed by either weave/docker0 for secondary interfaces. Hiding veth*, vxlan* and datapath interfaces by default as these aren't important to show in the vSphere UI

Ensuring eth0 interface is shown first in vSphere UI

---

examples/powercli/datastore-usage-email/README.md
examples/powercli/datastore-usage-email/handler/script.ps1

Allows SMTP_PASSWORD and SMTP_USERNAME to be blank in the JSON config - if both are blank, unauthenticated SMTP on port 25 will be sent.
Added green alarm status for notification when alarm returns to normal.
Adjusted the email body language to match the alarm status.

Added unauthenticated SMTP and green status emails

---

files/setup-01-os.sh
files/setup.sh
manual/photon.xml.template
photon-version.json
test/deploy_veba_openfaas_processor.sh

Resolves https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/74 
**Testing:**
Deployed w/custom CIDR for Docker Bridge (e.g. `172.30.0.1/16`) and verified that the new CIDR was being used by Docker:

Support Customizing Docker Bridge Network

---

vmware-event-router/internal/processor/aws_event_bridge.go

Use interface in the EventBridge processor to enable mocking in unit
tests.
Related issue: #69

Make EventBridge client interface

---

build.sh
files/setup-05-event-processor.sh
photon.json
scripts/photon-settings.sh
test/deploy_veba_eventbridge_processor.sh

Closing https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/91
Version/Commit ID is generated from the build.sh script and passes that into Packer as environmental variables which is then used to construct the initial `/etc/veba-release` file. Upon first boot after a user configures VEBA, the processor type is appended to the file. 
Testing was done on both OpenFaaS and AWS Event Bridge and below are the outputs when cat'ing `/etc/veba-release`
```
Version: v0.3.0
Commit: 634263b
Processor: OpenFaaS
```
```
Version: v0.3.0
Commit: 634263b
Processor: EventBridge
```

Add /etc/veba-release to include VEBA version, commit ID & event processor

---

scripts/photon-containers.sh

> Summary
The current method in which the Weave YAML is being downloaded from is not stable, meaning changes upstream can negatively affect things like change in Weave container image, which is what happened. Instead, we are no pulling the YAML from Weave github repo with a specific commit which ensures the version of the container we're using will always work. With this change, I've gone ahead and rev'ed to the latest version which is `2.6.2`
> Resolves
Close: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/102
> Testing
Deployed VEBA w/OpenFaa Processor against vSphere 6.7u3b and vSphere 7.0 build and verified the following:
Desired version of weave containers have already been downloaded:
```
root@veba [ ~ ]# docker images
REPOSITORY …
```

Pull Weave YAML from Git repo versus dynamic URL

---

vmware-event-router/Makefile

Support a `:$VERSION` tag based on the content of the `VERSION` file.
`make push` to push the images will only work when in `master`branch.
This is to prevent pushing an image with a `:VERSION` tag from any
branch != `master`.
Closes: #102

Add Docker image for :VERSION tag

---

files/setup-06-event-router.sh
photon.json
scripts/photon-containers.sh

> Summary
Updated the logic on how the VMware Event Router image is pulled per https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/105 and fixed Event Router K8s YAML to reflect the image version + imagePullPolicy for airgap/non-internet requirement
> Resolves
Close: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/102
> Testing
**Internal:** Deployed VEBA w/OpenFaa Processor against vSphere 7.0 build and verified deployment was successful and all pods were running as expected
**External:** Provided a build w/fixes to customer which has been verified https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/102#issuecomment-611537305

Fix VMware Event Router image pull to support air-gap scenario

---

examples/python/trigger-pagerduty-incident/README.MD
examples/python/trigger-pagerduty-incident/handler/handler.py
examples/python/trigger-pagerduty-incident/handler/requirements.txt
examples/python/trigger-pagerduty-incident/pdconfig.json
examples/python/trigger-pagerduty-incident/stack.yml

Created a simple Pagerduty function that will make a rest API call triggering a Pagerduty Incident upon a vCenter Event. 
Function was tested on vCenter 6.7, Pagerduty(SaaS) and VEBA 0.3(w/ OpenFaaS) with VMPowerOn/Off Events. For convenience, additional unit tests are provided within the handler.py for quick local testing of the function. 

Add invoke PagerDuty Incident sample function

---

files/setup-01-os.sh
files/setup-04-kubernetes.sh
manual/photon.xml.template
scripts/photon-containers.sh
scripts/photon-settings.sh

> Summary
This changes contains the configuration updates to support Antrea as the default CNI instead of Weave. v0.6.0 was used as it contained a fix which was identified during the research phase. 
> Resolves
Closes: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/16
> Testing
Deployed VEBA w/OpenFaa Processor against vSphere 7.0 build and verified deployment was successful and all pods were running as expected

Replace Weave with Antrea CNI 

---

.github/create-docker-release.yml

After a release is published, the corresponding Github event will
trigger this workflow to build and push the Docker images for the VMware
Event Router as per the Makefile target `make release`.
Github secrets (encrypted) for `DOCKER_USER` and `DOCKER_SECRET` are
used to authenticate. These secrets are not exposed through the UI and
not persisted after the workflow terminates as per the Github Actions
documentation.
Tested successfully in a fork of this repository:
> **Note:** Github (Actions) automatically hides sensitive information from the logs, e.g. secrets. The Docker password warning can be ignored as the Github Actions runner (using Microsoft Azure compliant VMs) will not be reused after a workflow run, i.e. each workflow runs in a fresh VM instance. …

Add Github Action to push Docker Images

---

vmware-event-router/Makefile
vmware-event-router/internal/processor/aws_event_bridge.go
vmware-event-router/internal/processor/aws_event_bridge_test.go

Adding input entry batching which means that
we will no longer send all events with single
PutEvents call, but rather will batch the
events and will send at most 10 with single
PutEvents call, thus honoring the AWS limits
of at most 10 entries per request. Also adding
execution of tests as step of the docker build
Closes: #69 
Signed-off-by: Martin Dekov <mvdekov@gmail.com>
1. Built image
2. Added unit tests
>Note: haven't tested in live environment but can help someone deploy the change if someone has live AWS environment

Add input entry batching

---

examples/python/invoke-rest-api/README.MD
examples/python/invoke-rest-api/handler/handler.py
examples/python/invoke-rest-api/handler/requirements.txt
examples/python/invoke-rest-api/metaconfig-jira.json
examples/python/invoke-rest-api/metaconfig-pduty.json
examples/python/invoke-rest-api/metaconfig-sdesk.json
examples/python/invoke-rest-api/metaconfig-slack.json
examples/python/invoke-rest-api/metaconfig-snow.json
examples/python/invoke-rest-api/metaconfig-zdesk.json
examples/python/invoke-rest-api/stack.yml

This function is the Postman or cURL for VEBA and can make a POST api call to any endpoint that supports basic, token auth in headers or no authentication. 
Sample configs provided for above mentioned endpoints
Debug messages print to stderr, does not show in FaaS Response. 
Unit tests available in handle.py, uncomment to test locally
**Testing**: 
Environment: vCenter 6.7 and VEBA v0.3(w/ OpenFaaS)
This function was tested against the following APIs/Systems (configs provided
- Slack (send message to a channel)
- PagerDuty (trigger an incident) and 
- ServiceNow (create an incident) 
- ServiceDesk (create a request)
- JIRA (create a JIRA issue)
- Zendesk (create a ticket) 

Add Function for Rest API Integrations (Slack, Pagerduty, JIRA, ServiceDesk, ZenDesk and ServiceNow)

---

manual/add_ovf_properties.sh

> Summary
This change removes the following `<vmw:ExtraConfig ovf:required="false" vmw:key="virtualhw.productcompatibility" vmw:value="hosted"/>` entry as its automatically generated after a VM is exported. This setting is not needed but the impact is it generates a warning message which can be seen as an issue
> Resolves
Closes: #123
> Testing
Deployed VEBA OVA using vSphere UI and ensure the following message `The OVF package contains advanced configuration options, which might pose a security risk. Review the advanced configuration options below. Click next to accept the advanced configuration options.` is no longer observed

Remove unnecessary vmw:ExtraConfig from OVA

---

.github/workflows/create-docker-prerelease.yml

This action is triggered on creation/push to release branches matching
any `release-*` branch name.
It will test, build and push a Docker image for the VMware Event Router
with the following tag structure: `vmware/veba-event-router:$VERSION`
where `VERSION` is the name of the release branch, e.g. `release-0.4`.

Add Github Action for Docker Pre-Release

---

.github/workflows/protect-master.yml

Even though branch protection rules might be in place, this is an
additional safety net to protect against unwanted pull requests against
`master`.
Should this action trigger, a corresponding failed check in the pull
request will indicate this visually.

Add Action to reject PRs against master

---

.github/workflows/router-unit-tests.yml

This action is triggered on pull requests but only when there are
changes to the `vmware-event-router` directory, incl. sub-directories.
The action will run the in the `Makefile` specified unit tests for the
VMware Event Router.

Add Action for Event Router Unit Tests on PRs

---

test/deploy_veba_eventbridge_processor.sh
test/deploy_veba_openfaas_processor.sh

Added variables VEBA_HTTP_PROXY, VEBA_HTTPS_PROXY, VEBA_PROXY_USERNAME, VEBA_PROXY_PASSWORD, and VEBA_NOPROXY to the deployment shell scripts.
Tested with VEBA 0.4 deployed on vCenter 7.0. 

Added proxy support for deployment scripts

---

examples/python/trigger-pagerduty-incident/README.MD
examples/python/trigger-pagerduty-incident/stack.yml

Updating container image from 'veba-pagerduty-invoke' to 'veba-python-pagerduty' for consistency 

Updating PagerDuty Fx container image name for consistency

---

manual/photon.xml.template

Added "Adding the appliance IP address is recommended." text to the No Proxy instructions in the OVA. This will 
Tested by executing an OVA build and navigating to the no_proxy input section - screenshot below:

Added recommendation to add appliance IP to NO_PROXY

---

files/setup-05-event-processor.sh

> Summary
It was identified that when deploying VEBA `v0.4.0` using the AWS EventBridge processor, that the system looks to hang and never completes. This change fixes a typo in processing the `ESCAPED_AWS_EVENTBRIDGE_EVENT_BUS` variable which causes the event processor script to fail (by design)
Here's snippet from the debug logs:
```
/root/setup/setup-05-event-processor.sh: line 30: VCENTER_USEAWS_EVENTBRIDGE_EVENT_BUSNAME: unbound variable
++ ESCAPED_AWS_EVENTBRIDGE_EVENT_BUS=
```
> Resolves
Closes: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/143
> Testing
Successfully deployed pre-release (v0.4.1) of VEBA using AWS EventBridge and confirm VEBA DCUI is properly loaded and no longer hangs. 

Fixed typo in processing ESCAPED_AWS_EVENTBRIDGE_EVENT_BUS variable

---

examples/powercli/datastore-usage-email/README.md
examples/powercli/datastore-usage-email/handler/script.ps1
examples/powercli/datastore-usage-email/vc-datastore-config.json

Support for a custom attribute added to the datastore containing an additional To: address.Gives vCenter admins the ability to configure recipient directly in vCenter without having to modify and push a new JSON secret.
Testing: Tested on vCenter 7 and VMC SDDC M9 with VEBA 0.3 release. Validated successful email delivery with all possible combinations of: authenticated SMTP, unauthenticated SMTP, custom attribute present, and custom attribute not present

Support datastore custom attribute as To: address

---

.github/workflows/check-wip-pr.yml

Perform `exit 1` if PR title starts with "WIP" to block accidental
merges of pull requests which are work in progress. Matches any title
which starts with "WIP", e.g. including "WIP:". Gets triggered on PR
open/edited/reopened and when (new) commits are (force) pushed.

Add Action to block PR merge when title is WIP

---

files/setup-01-os.sh
files/setup.sh
manual/photon.xml.template
test/deploy_veba_eventbridge_processor.sh
test/deploy_veba_openfaas_processor.sh

Add an Enable SSH checkbox in the OVA GUI. Update the automation scripts in /test to also support enabling SSH on deployment. Fixed issues in the automation scripts caused by unexpected spaces added by Windows - edited them in Linux instead.
Testing:
1. Deploy from UI, check SSH box. Expected behavior: SSH running on boot. Result: Success
2. Deploy from UI, uncheck SSH box. Expected behavior: SSH not running on boot. Result: Success
3. Deploy from deploy_veba_openfaas_processor.sh, VEBA_ENABLE_SSH="True". Expected behavior: SSH running on boot. Result: Success
4. Deploy from deploy_veba_openfaas_processor.sh, VEBA_ENABLE_SSH="False": SSH running on boot. Result: Success

Added enable SSH option to OVA install

---

manual/photon.xml.template

Add a FQDN hint to the _Hostname_ description field of the OVF template to make it more obvious for the user to enter the Fully-Qualified-Domain-Name of the appliance here.
Example:

Add FQDN hint to hostname description field

---

files/setup-02-proxy.sh
manual/photon.xml.template

If a http(s):// prefix is specified for either HTTP or HTTPS Proxy OVF properties, then use that rather than assuming either.

Allow use of "http://" prefix in HTTPS Proxy config

---

docs/_data/default.yml
docs/kb/contribute-functions.md
docs/kb/contribute-start.md
docs/kb/intro-about.md

**Issues**
1. CTA URL broken on the Documentation landing page
2. Standardizing on URL for all the documentation md (remove '/kb/') files

Track and Fix website issues

---

docs/README.md

Using a mac, I needed to do this to test a change in the docs.
* `gem ... --user-install` to avoid using sudo
* use a vendor dir that is outside of the docs tree
Signed-off-by: Tom Scanlan <tscanlan@vmware.com>

install gems only for the user, and set a vendor path for bundle use

---

vmware-event-router/internal/processor/aws_event_bridge.go
vmware-event-router/internal/processor/processor.go
vmware-event-router/internal/processor/processor_test.go

Introducing Error struct in processor package next to the
interface, to be used by the Process method to extend the
errors with more context by providing the name of the
processor
Signed-off-by: Martin Dekov <mvdekov@gmail.com>

Introduce Error struct in processor

---

.github/workflows/router-unit-tests.yml
vmware-event-router/Dockerfile

Update Golang linter to latest version. Unit tests will now also verify
whether container image can be build.
Closes: #128 

Update Linter and Unit Test Action

---

vmware-event-router/Dockerfile

Dockerfile build and deploy stage will use latest available Docker
images for Golang/Debian as of filing this commit.
Closes: #167 

Update Docker images used in VMware Event Router

---

build.sh
files/kubeconfig.yml
files/setup-04-kubernetes.sh
photon-version.json
photon.json
scripts/photon-containers.sh
scripts/photon-settings.sh
veba-bom.json

> Summary
This change leverages the `veba-bom.json` file which contains the build of materials (BOM) for all components of VEBA including the individual containers and their respective versions. 
This can be used for informational purposes but will also serve as a single source of truth for what versions are automatically downloaded as part of building VEBA. A copy of the BOM will also be pushed into the appliance and stored under `/root/config/veba-bom.json` a reference point.
> Commit Details:
* 8895230e9746538d62d7adaa5c47a8cb8d61ceb6 - Refactors VEBA components to reference `veba-bom.json`
* 88bd3f29ae4a396814dbcfd829f41af01865cd9e - Update K8s to `v1.18.3`, Contour to `v1.4.0` and OpenFaaS to `0.10.5`
> Resolves
Closes: https://github.com/vmware-samples/vcenter-event-broker-appliance/ …

Refactoring VEBA component reference + updating components to latest version 

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-enhancement.md

> Summary
Introduce Github template for filing VEBA Issues/Bug as well as Feature Enhancements
**Bug Report Template**:
- Default Assignee: N/A
- Default Label: Bug
**Feature Enhancement Template**:
- Default Assignee: @lamw 
- Default Label: Enhancement

Github Issue Templates for VEBA Bug Report and Feature Enhancements

---

README.md
docs/_config.yml
docs/index.html
docs/kb/install-eventbridge.md
docs/kb/install-openfaas.md
docs/kb/intro-about.md
docs/zcleanup/getting-started.md

Link change to reference the new flings URL  vmware-event-broker-appliance instead of vcenter-event-broker-appliance. The redirect works currently but we might as well reference the correct link.
Tested by clicking the link on local webserver.

Updated Fling URL from vcenter to vmware

---

docs/site/examples.md
examples/powercli/ha-restarted-vms/README.md
examples/powercli/ha-restarted-vms/handler/script.ps1
examples/powercli/ha-restarted-vms/stack.yml
examples/powercli/ha-restarted-vms/template/powercli/Dockerfile
examples/powercli/ha-restarted-vms/template/powercli/function/script.ps1
examples/powercli/ha-restarted-vms/template/powercli/template.yml
examples/powercli/ha-restarted-vms/vcconfig-ha-restarted-vms.json

This example demonstrates using VEBA and PowerShell/PowerCLI to send an email notification listing all VMs which were restarted due to a host failure in an HA enabled cluster.
Testing environment:  vCenter 6.7 and VEBA v0.4 & 0.4.1 (w/OpenFaas)
Tested by "forcefully" restarting/resetting physical server causing an HA fail over event.
Signed-off-by:  rkt6865 robert_terra@brown.edu

Add function HA Restarted VMs Email Notification

---

files/setup-05-event-processor.sh
files/setup-06-event-router.sh

This change incorporates the new YAML format that the VMware Event Router accepts, previously this was JSON format. The default port for Event Router stats of 8080 has also changed to 8082 (internal) to prevent collision for local development purposes. 
* N/A
* Successfully deploy VEBA appliance using pre-release version (69c6d93) of VMware Event Router that uses YAML and ensures all pods are up and running and that Event Router is successfully started and processing vCenter Events. 
```
root@veba [ ~ ]# kubectl -n vmware logs vmware-event-router-6f764588cd-xcl9p | head -20
_    ____  ___                            ______ …
```

Integrate new YAML format for VMware Event Router

---

vmware-event-router/internal/events/events.go
vmware-event-router/internal/provider/vcenter/checkpoint.go
vmware-event-router/internal/provider/vcenter/checkpoint_test.go
vmware-event-router/internal/provider/vcenter/vcenter.go

This change adds the last event UUID processed to the checkpoint to ease
troubleshooting and visibility into checkpointing.
The updated file format is:
```json
{
"vCenter": "10.0.0.1",
"lastEventUUID": "f8d71cb0-fd66-4e3b-aae1-b62d4576bf40",
"lastEventKey": 26071,
"lastEventType": "UserLogoutSessionEvent",
"lastEventKeyTimestamp": "2020-10-13T08:05:36.792Z",
"createdTimestamp": "2020-10-13T08:05:55.534638Z"
}
```
What …

Add event UUID to checkpoint

---

vmware-event-router/Makefile

Fix for Makefile only running gofmt against `cmd`.
n/a
Unit/integration tests pass.
n/a

Include all files in gofmt

---

examples/python/pre-filter/.gitignore
examples/python/pre-filter/README.md
examples/python/pre-filter/pre-filter/handler.py
examples/python/pre-filter/pre-filter/unit_tests.py
examples/python/pre-filter/stack.yml

* Refactored the pre-filter function to enable filtering against all data fields and make it leaner and faster
* Can now specify if all defined filters must match
* Handles traversing in to dicts/lists in the event data
* Added functionality to use 'n' in numeric indices of lists
* Added faas stack tracing support
* Unit tests significantly improved
* Documentation updates and improved logging
These changes allow the pre-filter function to be used to apply filtering against any data in the received CloudEvent data, including traversing in to dicts and lists in the event data.
The original ability to filter against vcenter object paths is retained and doesn't change.
What types of …

Pre-filter example function allows filtering against all CloudEvent data

---

vmware-event-router/go.mod
vmware-event-router/go.sum

Uses a recent version of the forked SDK to improve the error handling
when credentials are missing or wrong but basic auth in the OpenFaaS
gateway is enforced.
⚠️  
**Note:** This PR is explicitly against the release branch (`v0.5.0`) to not delay this enhancement due to several issues faced during release testing caused by this error message.
Instead of this rather useless error message due to wrong OF gateway credentials:
```bash
_    ____  ___                            ______                 __     ____              __
| |  / /  |/  /      ______ _________     / ____/   _____  ____  / /_   / __ \____  __  __/ /____  _____
| | / / /|_/ / | /| / / __  / ___/ _ \   / __/ | | / / _ \/ __ \/ __/  / /_/ / __ \/ / / / __/ _ \/ ___/
| |/ / /  / /| |/ |/ / /_/ / /  /  __/  / /___ | |/ /  __/ / …
```

Bump OpenFaaS SDK version

---

files/setup-05-event-processor.sh
veba-bom.json

In addition to the faas-idler:0.3.0 version no longer being available on dockerhub, it looks like faas-idler component is no longer part of the latest release of OpenFaaS. With the current version of OpenFaaS that is being used, we are unable to build VEBA appliance. This change updates OpenFaaS to the latest release 0.12.15 (at the time of testing) along with the required container images that are reflected in the VEBA bom file.
* Closes #292 
Successfully built and …

Update to OpenFaaS 0.12.15

---

scripts/photon-settings.sh

This change introduces the enablement of log rotation for the contrackd logs. This has negatively impacted customers as there is currently no default log rotation for the contrackd stats logs which can/has filled up the filesystem on VEBA.
* Closes #294 
Successfully built and deployed VEBA appliance w/log rotation configured for the contrackd service
```
cat /etc/logrotate.d/contrackd
/var/log/conntrackd*.log {
missingok
size 5M
rotate 3
maxage 7
compress
copytruncate …
```

Configure log rotation for contrackd

---

veba-bom.json
vmware-event-router/hack/run_integration_tests.sh

This change updates the version of K8s to the latest v1.20.2 release.
* Closes #293 
Successfully built and deployed VEBA appliance w/K8s 1.20.2
```
k get nodes -o wide
NAME                          STATUS   ROLES                  AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                 KERNEL-VERSION   CONTAINER-RUNTIME
veba.primp-industries.local   Ready    control-plane,master   127m   v1.20.2   192.168.30.9   <none>        VMware Photon OS/Linux …
```

Update to K8s 1.20.2

---

files/setup-01-os.sh
files/setup-04-kubernetes.sh

This change introduces a check that only setups the local storage provisioner configuration when VEBA is deployed using the embedded Knative deployment model. For both OpenFaaS and EventBridge, this configuration is not required and should not be setup.
* Closes #304 
Verified `/data/local-path-provisioner` is not created on filesystem nor local-path-provisioner containers are deployed

Deploy local storage provisioner only for embedded Knative

---

files/setup-03-network.sh

This change fixes the automatically reverting to the local DNS stub resolver address of `127.0.0.53` in `/etc/resolve.conf` which breaks local DNS resolution.
* Closes #310 
Successfully built and deployed VEBA Appliance:
Verified `/etc/resolve.conf` does not automatically revert back to default DNS local stub address `127.0.0.53`
```
root@veba [ ~ ]# cat /etc/resolv.conf
nameserver 192.168.30.2
search primp-industries.local
```
Verified successful DNS lookup (short …

Fix /etc/resolv.conf from reverting back to local DNS stub address

---

examples/knative/python/kn-py-vm-attr/function.yaml

I the PR review of this function I gave the wrong advice to use `latest` tag. This fixes it. Image is pushed correctly to the registry.
Closes: #437
* Please include any relevant screenshots and/or output as part of the …

Use 1.0 tag for py-vm-attr image

---

files/eventbridge-ingressroute-gateway.yaml
files/knative-embedded-ingressroute-gateway.yaml
files/knative-embedded-veba-ui-ingressroute-gateway.yaml
files/knative-external-ingressroute-gateway.yaml
files/openfaas-ingressroute-gateway.yaml
files/setup-012-cadvisor.sh
files/setup.sh
photon.json
veba-bom.json

This PR will make cAdvisor an integral part of VEBA and will give customers a new url (`https://veba-fqdn/top`) to see resource usage and utilization. It will also improve support for Day-2 operations by providing an endpoint to which external monitoring solutions can connect to.
Closes #450
* successfully built and deployed VMware Event Broker Appliance
* validated the functional state of the cAdvisor deployment as well as the corresponding `httpproxy` …

Add resource usage and performance monitoring feature

---

examples/knative/templates/server.ps1

Signed-off-by: Dimitar Milov <dmilov@vmware.com>
Improves the server.ps1 implementation with tha ability to process multiple events sent simulteniously.
Addresses issue #495 
- HttpListener is opened only once at the beginning
- HttpListener is closed only when server stop request is received (usually by process SIGTERM)
- HTTP Requests are enqueued and processed one by one allowing multiple simultenious requests to the server to be sent.
Closes #495 
* Short summary of testing (e.g. successfully built and …

Fix processing simultaneous requested events from different sources

---

examples/knative/templates/server.ps1
examples/knative/templates/test/process-init-error-handler.ps1
examples/knative/templates/test/server-test-helper.ps1
examples/knative/templates/test/server.tests.ps1

Signed-off-by: Dimitar Milov <dmilov@vmware.com>
Fix setting exit code for a `pwsh` process. Using the keyword `exit` doesn't set the process exit code when it is called from a worker thread. Using the .NET `System.Environment` `Exit` method works. It correctly sets the process exit code when called in a worker thread.
Closes #578
Tested exit code in isolation of VEBA on Windows and Photon OS container
Server code
```
$backgroundServer = Start-ThreadJob {
Start-Sleep -Seconds 1
[Environment]::Exit(1)
}
$running = …
```

fix: Fix settings process exit code in server.ps1

---

files/downloads/knative-contour/overlay.yaml

Closes: #689
Change knative-contour YAML imagePullPolicy from `Always` to `IfNotPresent` to support VEBA deployments in an air-gapped environment. 
* Manual testing to verify `imagePullPolicy` does not contain `Always`
* User verified through a custom OVA build incororpating this fix

Update imagePullPolicy for knative-contour for air-gap deployments

---

docs/kb/install-knative.md
files/configs/kubernetes/templates/kubeconfig-template.yaml
files/setup-01-os.sh
files/setup-02-proxy.sh
files/setup-04-kubernetes.sh
files/setup.sh
manual/photon.xml.template
scripts/photon-containers.sh
scripts/photon-docker.sh
scripts/photon-settings.sh
veba-bom.json
vmware-event-router/hack/run_integration_tests.sh

Closes: #674 
Verified VEBA appliance build is successful in switching container runtime
```
root@veba [ ~ ]# kubectl get nodes -o json | jq -r .items[].status.nodeInfo
{
"architecture": "amd64",
"bootID": "d9d7d255-702b-4cc9-ad9d-35d6a1926365",
"containerRuntimeVersion": "containerd://1.5.7",
"kernelVersion": "5.10.61-3.ph4-esx",
"kubeProxyVersion": "v1.21.5",
"kubeletVersion": "v1.21.5",
"machineID": "289cc3f5f06646188f858cb3b363eab8",
"operatingSystem": "linux",
"osImage": "VMware Photon OS/Linux", …
```

Migrate container runtime from Docker to Containerd

---

files/configs/fluentbit/templates/fluentbit-configmap-template.yaml
files/configs/fluentbit/templates/fluentbit-ds-template.yaml

Closes: #721
Since we now changed the container runtime from Docker to Containerd (#678), the Fluentbit configuration has to be updated in order to fix issue #721 and to finally process all logs now.
Closes: #721
* All configuration changes were tested against a latest `development` build
Log output from an invoked `kn-pcli-tag` function:
Log output from an invoked `kn-pcli-nsx-tag-sync` function:

Update fluentbit config in order to process all logs

---

files/downloads/knative-contour/overlay.yaml
files/setup-05-knative.sh
veba-bom.json

This change adds support for latest Knative Eventing/Serving at v1.8.3 which also requires updates to several other dependencies:
- knative-contour v1.8.1
- rabbitmq-operator v1.14.0
- rabbitmq-broker v1.8.3
- rabbitmq-messaging-topology-operator v1.10.0
- cert-manager v1.10.0
Closes #984 
* Successfully built VEBA appliance with BOM and deployed appliance and verified that …

feat: Bump Knative Eventing/Serving to v1.8.3

---

scripts/photon-containers.sh

This change removes the need to pull the `kind` node container image into VEBA appliance as that is only needed for local development purposes.
Closes #993 
* Successfully built and deployed VEBA appliance and ensure kind node is no longer being pulled
```
IMAGE                                                                         TAG                 IMAGE ID            SIZE …
```

fix: Remove kind node image from VEBA appliance

---

.github/workflows/codeql-analysis.yml
.github/workflows/gcr-dev-image.yml
.github/workflows/gcr-prerelease-image.yml
.github/workflows/release.yml
.github/workflows/router-build.yml
.github/workflows/router-helm.yml
.github/workflows/router-integration-tests.yml
.github/workflows/router-lint.yml
.github/workflows/router-unit-tests.yml
vmware-event-router/.golangci.yml
vmware-event-router/.goreleaser.yaml

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/ …

fix: workflows

---

scripts/photon-settings.sh
veba-bom.json

This change replaces the "default" pause container version for containerd with the version specified in the VEBA BOM. This also ensures that VEBA can run in an air-gapped environment as it will not attempt to pull default version of pause container
Closes: #1085
* Deployed VEBA appliance and ensure only pause container 3.8 is deployed and no other versions are required
* Any other …

fix: Replace Containerd config with pause container from VEBA BOM

---

files/setup-05-knative.sh

PR will introduce a new waiting condition to the script which is doing the Knative setup. The wait condition is for the `RabbitMQCluster` object. 
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes Closes: #1167
* Ran new build
* Validated the new change during bootstrap process of VEBA
* Deployment (air-gapped) successfully multiple times

Add new wait condition to setup-05-knative.sh
