README.md
=> Fix dead link to contributing guide

examples/powercli/hwchange-slack/README.md, examples/powercli/hwchange-slack/handler/script.ps1, examples/powercli/hwchange-slack/stack.yml, examples/powercli/hwchange-slack/template/powercli/Dockerfile, examples/powercli/hwchange-slack/template/powercli/function/script.ps1, examples/powercli/hwchange-slack/template/powercli/template.yml, examples/powercli/hwchange-slack/vcconfig.json
Signed-off-by: opvizordz <dzimmer@opvizor.com>
=> new example VM reconfigure to Slack

examples/README.md
Signed-off-by: Doug Taliaferro <dougt42@gmail.com>
=> Add host maintenance example to README

examples/python/tagging/README.MD
Hopefully I did this correctly, it's my very first pull request.
=> Fixed typo 'read_debuge -> read_debug'

FAQ.md
=> Update FAQ with current WIP/TODO items

getting-started.md
Missed this file in my previous PR
=> Fixed provider name, read_debug, and faas-cli typo

getting-started.md, manual/photon-dev.xml.template, manual/photon.xml.template
* Addressed @kremerpatrick [feedback](https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/21) on ability to specify multiple DNS Server(s) 
* Updated README to include [details on mapping vCenter Server Events](https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/22)
* Minor typo/fixes
=> Updated DNS desc + vCenter Event Mapping Details

examples/powercli/eventbridge/README.md, examples/powercli/eventbridge/eventbridge-secrets.json, examples/powercli/eventbridge/handler/script.ps1, examples/powercli/eventbridge/stack.yml, examples/powercli/eventbridge/template/powercli/Dockerfile, examples/powercli/eventbridge/template/powercli/function/script.ps1, examples/powercli/eventbridge/template/powercli/template.yml
re-submitted (accidentally deleted pull request). Addressed all feedback including latest comments regarding README
=> EventBridge sample

files/setup.sh, manual/photon-dev.xml.template, manual/photon.xml.template, photon-dev.json, scripts/photon-containers.sh
=> Update default POD CIDR 10.99.0.0/20 & made it configurable

manual/photon-dev.xml.template, photon-dev.json
Fixes missing NTP lines in *-dev files.
=> Add NTP to photon-dev.xml.template photon-dev.json

examples/README.md
=> Add AWS EventBridge sample to example README

files/setup.sh
Fixes #48 
Proxy settings are now also set for Docker.
**Tests**:
```
1579732349.911      0 10.10.14.5 TCP_DENIED/403 3915 CONNECT registry-1.docker.io:443 - HIER_NONE/- text/html
1579732366.620      0 10.10.14.5 TCP_DENIED/403 3915 CONNECT registry-1.docker.io:443 - HIER_NONE/- text/html
```
```
1579732395.099    466 10.10.14.5 TCP_TUNNEL/200 5803 CONNECT registry-1.docker.io:443 - HIER_DIRECT/3.224.75.242 -
1579732395.575    474 10.10.14.5 TCP_TUNNEL/200 9798 CONNECT auth.docker.io:443 - HIER_DIRECT/34.201.196.144 -
1579732396.101    522 10.10.14.5 TCP_TUNNEL/200 7850 CONNECT registry-1.docker.io:443 - HIER_DIRECT/3.224.75.242 -
```
=> Adjusting proxy configuration for Docker

README.md
Here's preview of what the badges would look like on the main README
=> Spruce up README with a few badges

examples/README.md, examples/powershell/vro/README.md, examples/powershell/vro/handler/script.ps1, examples/powershell/vro/stack.yml, examples/powershell/vro/template/powercli/Dockerfile, examples/powershell/vro/template/powercli/function/script.ps1, examples/powershell/vro/template/powercli/template.yml, examples/powershell/vro/vro-secrets.json
This example demonstrates using VEBA to trigger vRO Workflow using vRO REST API
=> vRO Function Example

README.md
Commented out the user stories section until we have the first stories
to share.
=> Remove User Stories

docs/8-veba-troubleshooting.md, getting-started.md
=> Add initial release of troubleshooting guide

docs/8-veba-troubleshooting.md
Per https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/94#issuecomment-608306965 Troubleshooting Doc has been updated. 
Signed-off-by: William Lam <william2003@gmail.com>
=> Updating Troubleshooting docs with correct path to config file

README.md
=> Add Otto to start page

files/setup-05-event-processor.sh
> Summary
Special characters in password and/or username for vCenter Server, such as UPN format (DOMAIN\username) will cause issues when Event Router JSON is constructed as the characters are not properly escaped. This PR resolves that problem
> Resolves
Close: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/79
> Testing
Deployed VEBA w/OpenFaa Processor against and vSphere 7.0 build and verified the Event Router contained the correctly transformed variables/input and the Event Router Pod successfully started without issues. 
=> Escape special characters in Event Router Config JSON

examples/go/tagging/README.MD, examples/powercli/datastore-usage-email/README.md, examples/powershell/vro/README.md, examples/python/esx-mtu-fixer/README.md, examples/python/tagging/README.MD, getting-started-build.md, getting-started.md
Consistent use of highlighting important sections in all markdown files with the following layout:
> **Note:** Lorem ipsum...
Using this markdown syntax:
```
> **Note:** Lorem ipsum...
```
=> Consistent use of Notes in markdown files

vmware-event-router/README.MD, vmware-event-router/hack/README.md
=> Update READMEs in VMware Event Router

docs/kb/troubleshoot-appliance.md
=> Updated docs to reflect new v0.4 path to event-router-config.json

docs/kb/contribute-functions.md
This fixes getting a 404 error. Tested locally.
=> fix broken link

veba-bom.json
=> Add VEBA build-of-materials (BOM) file

veba-bom.json
=> Add faas-cli version to BOM

docs/kb/install-eventbridge.md, docs/kb/install-openfaas.md
Updating docs to reflect changes within
PR#147: Enable/Disable SSH when deploying the appliance
PR#161: Allow specifying the protocol when specifying the proxy
Tested previously on:
https://veba.pdotk.com/kb/install-eventbridge
https://veba.pdotk.com/kb/install-openfaas
=> Updating docs to reflect changes with Proxy and SSH

.github/PULL_REQUEST_TEMPLATE.md
Here's my initial [proposal for the VEBA PR template:
Would like to get some feedback
=> Github Template to standardized Pull Requests

.github/workflows/create-docker-prerelease.yml, .github/workflows/create-docker-release.yml
Shorten some workflow names for better readability in the Actions overview.
=> Shorten workflow names

.github/workflows/stale-issues.yml
Will warn the user after 30d on stale issues by applying a `stale` label. After another 5d of inactivity the issue will be closed.
Exceptions:
- Issue has one of the following labels: `awaiting-approval,work-in-progress,wip`
- Issue is updated after the warning
* Closes #191 
* Tested it locally with `act` Github Actions simulator but can only tell if it really works once it's merged :/
=> Add Github Action to close stale issues

examples/java/veeam-vm-backup/README.MD, examples/java/veeam-vm-backup/veeam-vm-backup.yml, examples/java/veeam-vm-backup/veeam-vm-backup/build.gradle, examples/java/veeam-vm-backup/veeam-vm-backup/settings.gradle, examples/java/veeam-vm-backup/veeam-vm-backup/src/main/java/com/openfaas/function/Handler.java, examples/java/veeam-vm-backup/veeamconfig.toml
* Closes #ISSUE-NUMBER
* Please include any relevant screenshots and/or …
=> Veeam-vm-backup function added

.gitignore, vmware-event-router/Dockerfile, vmware-event-router/README.MD, vmware-event-router/cmd/router/main.go, vmware-event-router/internal/config/v1alpha1/processor.go, vmware-event-router/internal/integration/suite_aws_test.go, vmware-event-router/internal/metrics/server.go, vmware-event-router/internal/processor/aws_event_bridge.go, vmware-event-router/internal/processor/aws_option.go, vmware-event-router/internal/processor/openfaas.go, vmware-event-router/internal/processor/openfaas_option.go
- Change to Ubuntu base image (Buster) to follow VMware OSPO guidance and
reduce number of CVEs compared to previous base image [1]
- Update README with required parameters
- Constructors in event processors return concrete types for better user
experience
[1]
CVEs before:
CVEs new: 
n/a
Unit and integration tests pass
n/a
=> Update build and README

.github/workflows/create-docker-dev-image.yml
This workflow will build and push an image for the `vmware-event-router`
on every push to the `development` branch but only if there are changes
to the `vmware-event-router` code base, i.e. folder (incl. sub-folders).
The image will be tagged with the `COMMIT_ID` of the (merge) commit, i.e. `vmware/veba-event-router:$COMMIT`
* Closes #216 
Tested against a private Github repo using Actions.
=> Add workflow to build image on dev branch

build.sh, docs/kb/contribute-appliance.md, manual/add_ovf_properties.sh, photon.json
Added support for Packer 1.6.x to support ESXi 7.0+
fixed bug in build.sh on CentOS
added min packer version
Updates to docs
Signed-off-by: David Bibby <davidsbibby@gmail.com>
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes …
=> Fix appliance build issues

.github/workflows/create-docker-dev-image.yml
This change will also build and push a `vmware/veba-event-router:development` image when a push is made to `development` branch.
* Closes #222
Build and pushed a test …
=> Build development image on push

files/setup-06-event-router.sh, files/setup-08-ingress.sh, scripts/photon-containers.sh, veba-bom.json
Update Contour to v1.9.0 which now uses HTTP Proxy instead of Ingress Route, which also required changes in the VMware Event Router configurations. 
Few minor changes in this PR includes:
* There was a change to the default Contour YAML which broke the build automation which is also resolved
* To prevent conflicts, the VMware Event Router for stats was changed from 8080 to 8082
* Rather than hardcoding the VMware Event Router container image/version, thats now being read from VEBA BOM (cleaned up as part of porting from Ingress Route to HTTP Proxy)
Please check …
=> Update to latest version of Contour

photon.json
The Packer configuration for VEBA now uses the VNC over websockets feature and no longer relies on the legacy VNC method. Removing `vnc_disable_password` will disable the following warning as it is no longer needed since it ignores all legacy vnc configurations
```
Warning: Warning when preparing build: "vmware-iso"
[WARN] When 'vnc_over_websocket' is set any other VNC configuration will be
ignored.
Warning: Warning when preparing build: "vmware-iso"
```
* N/A
* …
=> Removing Packer vnc_disable_password

examples/java/plugin-auto-refresh/Dockerfile, examples/java/plugin-auto-refresh/README.MD, examples/java/plugin-auto-refresh/VebaController.java, examples/java/plugin-auto-refresh/plugin-auto-refresh.yml, examples/java/veeam-vm-backup/README.MD
Plugin auto-refresh function triggers automatic refresh of the UI of a vSphere Client plugin after data changes. This flow is demonstrated using the vSphere Client SDK remote-plugin-sample - the chassis' list of hosts is automatically refreshed when updated remotely.
Signed-off-by: Mirela Manoleva <mmanoleva@vmware.com>
Please check the type of change …
=> Function for plugin auto-refresh

vmware-event-router/hack/run_integration_tests.sh
Fix security vulnerability described in:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* Closes #224 
n/a
n/a
=> Remove set-env references

files/setup-01-os.sh
Signed-off-by: David Bibby <davidsbibby@gmail.com>
Proposed fix for issue #211 
If we stop the docker service at the top of `setup-01-os.sh` this will allow network and proxy configs to take place. `setup-04-kubernetes.sh` already contains code to start and enable the docker service again. 
Marked as WIP as I've not yet rebuilt the appliance to test in full. 
* Closes #211 
* Tested …
=> Fix Docker proxy issue

vmware-event-router/internal/provider/vcenter/vcenter.go
vcenter event provider used the wrong lock type.
n/a
Unit tests pass with race flag.
n/a
=> Fix lock in vcenter

vmware-event-router/Dockerfile
Pinning certificates in the `Dockerfile` can fail if the version is removed. This change will always use the latest available certificates from the configured core apt sources.
Unblocks #241 
`make build` succeeds
n/a
=> Always use latest certificates

vmware-event-router/README.MD
Add details about vCenter events to README
n/a
n/a
n/a
=> Add details about vCenter events to README

vmware-event-router/internal/processor/aws/aws_event_bridge.go
Hide pattern map access through concurrency-safe and easier to use methods, also optimizing lock spans in the AWS processor.
n/a
Unit/integration tests pass.
n/a
=> Reduce pattern map lock contention

.github/workflows/router-lint.yml, vmware-event-router/Dockerfile, vmware-event-router/Makefile, vmware-event-router/internal/integration/events_test.go, vmware-event-router/internal/processor/openfaas/openfaas_test.go, vmware-event-router/internal/provider/fake/vcenter_fake_test.go, vmware-event-router/internal/provider/vcsim/vcsim_test.go
This change moves the linting out of the Docker build process to speed
up builds. Linting will be done using the official `golangci-lint`
Github Action. The action runs on all pushes (any branch) and PRs.
Go files with `unit` or `integration` tags will now be included. Linting
fixes are included as part of this commit.
* Closes #253 …
=> Make linter standalone action

.github/workflows/router-lint.yml, vmware-event-router/.golangci.yml
Github Action takes longer to process thus increasing timeout to avoid
errors (exit 1).
Also increase DEBUG output and formatted the YAML file.
* Closes #256 
Verified with a local Docker runner in a CPU constrained environment.
n/a
=> Increase timeout for Linter

README.md
Add Status Badges for Router Actions to README.
n/a
n/a
n/a
=> Add Status Badges for Router Actions

.github/workflows/create-docker-dev-image.yml, .github/workflows/create-docker-prerelease.yml, .github/workflows/router-unit-tests.yml, .github/workflows/router-verify-build.yml, README.md, vmware-event-router/Dockerfile, vmware-event-router/Makefile
This change parallelizes some Actions and always verifies that go
modules are in sync.  Instead of a linting badge, the README will now
show whether development builds of the router succeed.
Dockerfile and Makefile use `-gomod=readonly` to prevent accidentally
adding/updating modules.
* Closes #261 
Tested in a forked repo. Note that …
=> Optimize Router Workflows

vmware-event-router/internal/processor/openfaas/openfaas.go
OpenFaaS processor will also use shutdown semantics used in Knative
processor to coordinate a concurrent shutdown while requests are
in-flight.  If the default waitTimeout (5s) is exceeded the graceful
shutdown will be aborted and the processor will stop by closing the
response channel.
* Closes #264 
Run router, trigger a long …
=> Use Waitgroup to track in-flight requests

manual/photon.xml.template
This change adds the Knative processor selection into the OVF definition so that a user can actually select Knative as an option. It looks like this changed was missed when reconciling my broken merge last week.
* Closes #273 
* Deployed local build of the VEBA appliance and ensured the dropdown selection for processors included Knative
N/A
=> Add OVF dropdown for Knative processor selection

examples/python/kn-echo/README.MD
Similar to the `of-echo` function this adds a Python example `kn-echo` to the documentation for the Knative processor.
* Closes #279
Tested in a Knative environment with rabbit broker (see documentation for output).
Making this PR against the release branch to include this documentation as part of the upcoming v0.5.0 release.
=> Create kn-echo example

docs/kb/install-eventbridge.md, docs/kb/install-knative.md, docs/kb/install-openfaas.md
- [X ] Documentation changes
* Closes #ISSUE-NUMBER
* Short summary of testing (e.g. successfully built and deployed …
=> Added firewall requirement for access to vCenter API

vmware-event-router/deploy/event-router-config-knative.yaml
Fixes the metadata `label` in event-router-config-knative.yaml sample from `router-config-aws` to `router-config-knative`
* Closes #289 
N/A
N/A
=> Fix metadata label for event-router-knative.yaml sample

vmware-event-router/README.MD, vmware-event-router/go.mod, vmware-event-router/go.sum, vmware-event-router/internal/config/v1alpha1/provider.go, vmware-event-router/internal/provider/vcenter/vcenter_test.go, vmware-event-router/internal/provider/vcsim/vcsim.go
With all the required fixes around event collector and simulator in
recent govmomi versions, we don't need to maintain a separate vcsim
provider anymore. The vcenter event provider will now work correctly
against a vcsim instance.
* Closes #285 
Unit and integration tests work. Added new unit tests for `vcenter` provider using vcenter …
=> Deprecate vcsim provider

docs/_layouts/function.html, docs/assets/_scss/_styles.scss, docs/assets/_scss/site/layouts/_function.scss, docs/assets/js/scripts.js, docs/site/examples-knative.md, docs/site/examples-openfaas.md
Updating the Functions page layout to accommodate breaking out the functions into two separate pages - one for knative and one for OpenFaaS
* Verified locally as well as built on GithubPages
=> Updating files to help users consume knative vs openfaas functions

files/setup-06-event-processor.sh, scripts/photon-containers.sh
This PR introduces two changes:
1) Fix `prometheus-rbac.yml` file which is missing `openfaas` namespace causing invocation count to always be 0 
2) Use K8s `apply` rather than `create` when deploying OpenFaas.  If not done, deployment is partially instaslled
* Closes #306 
Successfully built and tested VEBA appliance with OpenFaaS function and ensure the invocation count is now incrementing when function is called. 
```
faas-cli list --tls-no-verify
Function …
```
=> Fix namespace bug in prometheus RBAC YAML + use "apply" instead of "create" for OpenFaaS deployment

photon-version.json
This change fixes the photonOS ISO download URL. Previously, the ISO was hosted on bintray and as VMware migrated off to a new repository which is now hosted on packages.vmware.com, the current URL is no longer valid.
* Closes #309 
Successfully built VEBA Appliance
N/A
=> Fix new PhotonOS ISO download URL 

files/setup-04-kubernetes.sh, files/setup-06-event-processor.sh, files/setup-07-event-router.sh, files/setup-09-ingress.sh, files/tinywww-debug.yml, files/tinywww.yml
This change renames the `vmware` namespace to `vmware-system` to make it explicit that this is for system related processes for VEBA. This change also introduces `vmware-functions` namespace which will make it clear for users where functions should be deployed
* Closes #311 
* Successfully built, deploy and test VEBA Appliance
N/A
=> Update naming on VMware namespaces

.github/workflows/stale-issues.yml
Periodically check for stale issues and PRs (new) with a higher timeout.
* Closes #318 
n/a
n/a
=> Update stale workflow

files/tinywww-debug.yml, files/tinywww.yml, veba-bom.json
This change updates the VEBA BOM file to pull the VMware specific container images from VMware Harbor instead of Docker and also updates the respective K8s manifest to now reference VMware Harbor URL
* Closes #316 
Successfully built and deployed VEBA Appliance and ensure VMware container images are now pulled from VMware Harbor repo
N/A
=> Updating VMware container image URLs to VMware Harbor

files/setup-05-knative.sh
This change disables the container digest check for Knative Serving, this is needed to use VMware Harbor Registry or deployment will fail. 
* Closes #332 
* Verified on VEBA appliance
N/A
=> Disable digest checking for Harbor Registry

files/setup-05-knative.sh, files/setup-09-ingress.sh, veba-bom.json
This change integrates Sockeye service into VEBA appliance such that users can open a browser to `/events` to view all events processed by Event Router
* Closes #320 
Verified HTTPS endpoint `/events` on VEBA appliance properly outputs events from Event Router
* N/A
=> Integrate Sockeye into VEBA

docs/_data/contributors.yml, docs/_includes/contributors.html
* Closes #331 
* Tested locally - screenshot attached
If you have any …
=> Adding code to include external contributors

docs/kb/intro-functions.md, docs/kb/use-functions.md, docs/site/examples-knative.md, examples/knative/powershell/kn-ps-echo/README.md, examples/knative/powershell/kn-ps-echo/function.yaml, examples/knative/powershell/kn-ps-slack/README.md, examples/knative/powershell/kn-ps-slack/function.yaml, veba-bom.json
This change ensures that that the VEBA UI only displays Knative Service/Triggers which have been annotated with `app-veba-ui" and ensures non-customer facing Knative Service/Triggers are not accidentally displayed or negatively impact the UI service. This change also includes documentation updates to reflect the required changes for users who wish to have their Knative Service/Trigger show up in VEBA UI
Closes #337
* Verified VEBA UI functions correctly w/the new …
=> Fixed VEBA UI image + Documentation Updates

examples/knative/powershell/kn-ps-echo/README.md, examples/knative/powershell/kn-ps-slack/README.md
This change fixes the typo for the Docker `push` command in the Knative PS Examples
* Closes #340 
N/A
N/A
=> Fix typo for Docker push command

files/setup-05-knative.sh
This change "undos" Issue #333 after Harbor Registry team made server side fix allowing us to re-enable Knative Serving's default behavior of digest checking
* Closes #342 
* Successfully built new VEBA Appliance w/Knative Service Digest Re-enabled (default behavior) and ensure function deployment was successful with immediate pull of container images from Harbor Registry
N/A
=> Re-enable Knative Serving registry digest check

examples/knative/powershell/kn-ps-slack/README.md
This change adds missing `vmware-functions` namespace to PS example where a new secret is created
* Closes #343 
N/A
N/A
=> Adding missing vmware-functions NS to secret example

docs/kb/install-knative.md, manual/photon.xml.template
Clarify OVF description so that it is clear for what is needed for either Embedded Knative deployment vs External Knative Installation
* Closes: #347 
* Verify documentation + OVF description
N/A
=> Clarifying Knative OVF description + Docs

examples/knative/powershell/kn-ps-slack/README.md
=> Add Windows specific Docker command to kn-ps-slack function

.github/PULL_REQUEST_TEMPLATE.md
=> Remove * in front of Closes keyword + Fix Typo in PR Template

vmware-event-router/chart/.helmignore
Adding the `releases/` line to `.helmignore` file to fixe issue #355.
This will avoid creating a helm secret with a size larger than the "per-secret size limit of 1MB".
Closes #355
Deployment (here its an upgrade from 0.5.0) from modified files works and events are well sent to the OpenFaaS endpoint.
```bash
helm upgrade --install -n  veba-vc1 veba-vc1 . -f values.yaml --version …
```
=> Fix #355 by helm-ignoring releases folder

docs/kb/install-knative.md
=> Document minimum vSphere Privileges for VEBA UI

.github/workflows/router-verify-helm.yml, vmware-event-router/deploy/vcsim.yaml
Runs helm chart deployment verification on every **change in the `chart/`
folder**.
Closes: #359
Closes #359 
=> Verify Helm chart release

docs/kb/intro-functions.md
=> Document multiple Knative Trigger examples

docs/kb/advanced-certificates.md
=> Update the correct cert name for TLS replacement

files/setup-06-event-processor.sh, vmware-event-router/deploy/event-router-config-aws.yaml
Closes #372 
Verified VMware Event Router is no longer showing invalid Event Bridge configuration
N/A
=> Add correct AWS Event Bridge Type into Event Router Config

veba-bom.json
Closes #371 
Verified in `rabbitmq-broker.yaml` manifest that all required container images are now incorporated into VEBA BOM
N/A
=> Add missing RabbitMQ Broker image to VEBA BOM

veba-bom.json
Closes #365 
* Provided early build to customer who ran into this problem and verified the fix
N/A
=> VEBA UI fix for incorrect TLS miss-match

files/eventbridge-ingressroute-gateway.yaml, files/knative-embedded-ingressroute-gateway.yaml, files/knative-embedded-veba-ui-ingressroute-gateway.yaml, files/knative-external-ingressroute-gateway.yaml, files/openfaas-ingressroute-gateway.yaml, files/setup-09-ingress.sh, photon.json
Closes #354 
* Verified Knative Embedded with and without VEBA UI configuration
* Verified OpenFaaS and EventBridge Processor deployments didn't regress
N/A
=> Refactor Ingress Configuration based on Processor Type

files/setup-01-os.sh, files/setup-09-ingress.sh
Closes #386 
Closes #381 
* Successfully deployed VEBA Appliance
N/A
=> Configure Docker Container Log Rotation + Sed Fix

.github/workflows/check-wip-pr.yml
Uses a dedicated Action instead of inline SHELL script.
Closes: #382
Tested in a staging repository with multiple test strings.
n/a
=> Update WIP Action

.github/comment-template.md, .github/workflows/issue-greeting.yml
Greet (only) first-time contributors when they open a new issue.
Closes: #390
Thank …
=> Add issue greeting

docs/kb/advanced-certificates.md
=> Update documentation to reflect new TLS certificate replacement in VEBA

.github/workflows/issue-greeting.yml
=> fix: Wrong association in greeting

.chglog/CHANGELOG.tpl.md, .chglog/config.yml
First step towards CHANGELOG automation. This procedure can be used to create a `CHANGELOG` after creating a release and also to create a continuously updated `CHANGELOG.md` file in the root of the repo.
Closes: #394
<a name="v0.6.1"></a>
> Release Date: 2021-05-05
- Add Helm Option for Knative
- Add issue greeting
- Document simplified steps for replacing TLS certifcate in VEBA [5e7c2e4]
- Bump Helm chart version to v0.6.2 [121c688]
- Add v0.6.2 Chart Pre-Release [f03672e]
- feat: Add Helm Option for Knative [4d503c9]
- chore: Add issue greeting [d0d93c8]
- Example Knative PowerShell Email Function [168abeb]
- Update WIP Action [11a83cd]
- Fix sed command [7f8177f]
- Configure container log rotation [5169b39]
- Add support for custom VEBA …
=> chore: Automate CHANGELOG

docs/kb/install-knative.md
=> fix: Update documentation to reflect minimum vCenter 7.0 for VEBA UI

docs/kb/advanced-certificates.md
=> fix: Fix command in adding trusted root CA cert documentation

.chglog/config.yml
Adds a `Documentation` section to the `CHANGELOG`.
<a name="v0.6.1"></a>
> Release Date: 2021-05-11
- Wrong association in greeting
- Document Trusted Root Certificate support w/VMware Event Router
- Add router support for custom certificates
- Add Helm Option for Knative
- test
- Automate CHANGELOG
- Add issue greeting
- docs: test [30229d7]
- feat: Document Trusted Root Certificate support w/VMware Event Router [eefe0d2]
- fix: Wrong association in greeting [0356447]
- chore: Automate CHANGELOG [2ef2aa1]
- feat: Add router support for custom certificates [b2507eb]
- Document simplified steps for replacing TLS certifcate in VEBA [5e7c2e4]
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this …
=> Add docs section to CHANGELOG

vmware-event-router/README.MD
=> Clarify vcsim deprecation

.github/workflows/router-verify-build.yml, .github/workflows/router-verify-helm.yml
=> chore: Daily build and helm verification

.chglog/CHANGELOG.tpl.md, .github/workflows/release-notes.yml, CHANGELOG.md
Closes: #422
- keep a CHANGELOG
- create PR on new release tag to update CHANGELOG
- CHANGELOG template formatting …
=> chore: Add CHANGELOG workflow

examples/knative/templates/Dockerfile.pcli, examples/knative/templates/Dockerfile.ps, examples/knative/templates/README.md, examples/knative/templates/server.ps1
=> feat: Add Knative Base PowerShell/PowerCLI Container Images

examples/knative/python/kn-py-echo/Procfile, examples/knative/python/kn-py-echo/README.md, examples/knative/python/kn-py-echo/function.yaml, examples/knative/python/kn-py-echo/handler.py, examples/knative/python/kn-py-echo/pyvenv.cfg, examples/knative/python/kn-py-echo/requirements.txt, examples/knative/python/kn-py-echo/test/testevent.json
Took Michael's kn-echo function and created kn-py-echo example in the format of the other examples in the repository.
- [ x] Please ensure that you are making a pull request against the **Development** branch
- [ x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [x ] Please make sure that you have tested your change locally by successfully …
=> Add kn-py-echo to examples folder 

docs/site/examples-knative.md
=> docs: Add new Python/Go examples to Docs

examples/openfaas/python/invoke-rest-api/handler/requirements.txt, examples/openfaas/python/tagging/handler/requirements.txt, examples/openfaas/python/trigger-pagerduty-incident/handler/requirements.txt
After the bot bumped urllib, functions could not be built anymore due to dep mismatch. This PR fixes this and all functions were correctly built and pushed.
Closes: #440
* Please include any relevant screenshots and/or …
=> Bump requests lib in OpenFaaS Python fns

.chglog/CHANGELOG.tpl.md
`BREAKING` section in `CHANGELOG` was missing details on the commit that introduces a certain breaking change.
- [4e4c8f7]     Add new Python/Go examples to Docs
- [8bb8949]     Update Knative Function list w/PowerShell Email Example
- [59590e8]     Update CHANGELOG template (#429)
- [0666a0a]     Add CHANGELOG workflow
- [a5a91d0]     Daily build and helm verification (#414)
- [2ef2aa1]     Automate CHANGELOG (#394)
- [d0d93c8]     Add issue greeting (#390)
Add vsphereapiversion to CE context [05caac1]:
This change sets the `timestamp` in the CloudEvent to the
`CreatedTime` as set by vCenter in a vSphere event instead of
`time.Now()`.
- [05caac1]     feat: Add vsphereapiversion to CE context (#439)
- [b894ab6]     Bump requests lib in …
=> Include commit details in BREAKING section

vmware-event-router/go.mod, vmware-event-router/go.sum, vmware-event-router/internal/events/events.go, vmware-event-router/internal/events/events_test.go, vmware-event-router/internal/integration/aws_test.go, vmware-event-router/internal/integration/openfaas_test.go, vmware-event-router/internal/provider/fake/vcenter_fake.go, vmware-event-router/internal/provider/vcenter/vcenter.go, vmware-event-router/internal/provider/vcsim/vcsim.go, vmware-event-router/vendor/gotest.tools/LICENSE, vmware-event-router/vendor/gotest.tools/assert/assert.go, vmware-event-router/vendor/gotest.tools/assert/cmp/compare.go, vmware-event-router/vendor/gotest.tools/assert/cmp/result.go, vmware-event-router/vendor/gotest.tools/assert/result.go, vmware-event-router/vendor/gotest.tools/internal/difflib/LICENSE, vmware-event-router/vendor/gotest.tools/internal/difflib/difflib.go, vmware-event-router/vendor/gotest.tools/internal/format/diff.go, vmware-event-router/vendor/gotest.tools/internal/format/format.go, vmware-event-router/vendor/gotest.tools/internal/source/defers.go, vmware-event-router/vendor/gotest.tools/internal/source/source.go, vmware-event-router/vendor/modules.txt
Since vSphere events are not versioned and (somewhat loosely) tied to a particular vSphere API version, this change introduces a new CloudEvents context attribute `vsphereapiversion` reflecting the vSphere API version of a particular CloudEvent produced by the `vcenter` event producer.
BREAKING: This change sets the `timestamp` in the CloudEvent to the `CreatedTime` as set by vCenter in a vSphere event instead of `time.Now()`.
Closes: #439
Closes #439
Tested …
=> Add vsphereapiversion to CE context

examples/knative/templates/README.md
=> docs: Update PS/PCLI Images to latest v1.1

.github/ISSUE_TEMPLATE/bug-report.md
* Please include any relevant screenshots and/or …
=> Add `[BUG]` to issue template title

.github/workflows/router-verify-helm.yml, vmware-event-router/README.MD, vmware-event-router/chart/templates/100_clusterrolebinding.yaml, vmware-event-router/chart/templates/400_deployment.yaml, vmware-event-router/chart/values.yaml, vmware-event-router/deploy/event-router-k8s.yaml
Helm verification will be run on every commit and PR on changes inside the `vmware-event-router` folder. Instead of using the currently pushed Helm chart image, a new image will be built using `ko` based on the current commit of the event router and used as part of the Helm chart deployment.
Additional changes:
- Helm values file allows for custom image tag, e.g. for testing
- Bump Knative version used in testing to v0.23.0
- Only install Helm chart `ClusterRoleBinding` when installing Knative processor
- Knative `ClusterRole` used is now `knative-serving-aggregated-addressable-resolver` to correctly set up `Listers` (fixes `"Lister" not found` issue)
- Fix `port: 8080` in router deployment YAML which should be `8082` which is the default of the metrics server
Closes: #464
Signed-off-by: …
=> chore: Update Helm chart workflow

files/setup-05-knative.sh, files/setup-07-event-router.sh
PR will adjust the `--timeout` values from `-1s`, which means _wait for a week_, to `3m` for the particular `setup` scripts `05` and `07`.
Closes: #468
* successfully built and deployed VMware Event Broker Appliance
* validated VEBA functionality
N/A
=> Adjust the kubectl wait timeout values in setup script 05 and 07

examples/knative/powercli/kn-pcli-tag/function.yaml, examples/knative/powershell/kn-ps-email/function.yaml, examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/python/kn-py-echo/function.yaml, examples/knative/python/kn-py-slack/function.yaml, examples/knative/python/kn-py-vm-attr/function.yaml
Closes: #474
This change fixes the annotation for describing scale to 1 configuration in Knative YAML examples and ensures all examples are consistent (e.g. annotation / labels)
* Please include any relevant screenshots …
=> docs: Fix YAML annotation for scale to 1

photon.json
This will change the disk configurations by increasing them to 25 GB.
Closes: #476
* successfully built and deployed VMware Event Broker Appliance
* validated increased disk configurations
```
root@veba-dev [ ~ ]# df -h | grep -vE '(overlay|tmpfs|shm)'
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        25G  4.5G   19G  20% /
/dev/sda2        10M  2.2M  7.9M  22% /boot/efi
/dev/sdb1        25G  380M   23G   2% /data
```
N/A
=> Increase disk space for the two vmdks from 12 GB to 25 GB each

docs/kb/use-functions.md, veba-bom.json
Closes: #448
This change introduces the ability to configure `minScale`, `maxScale` and `containerConcurrency` settings for a given function deployment using the VEBA UI
Using values of 1,1,1 will result in Knative Service that looks like the following:
```console
...
Spec:
Template:
Metadata:
Annotations:
autoscaling.knative.dev/maxScale:  1
autoscaling.knative.dev/minScale:  1
Creation Timestamp:                  <nil>
Spec:
Container Concurrency:  1
....
```
=> Add scaling and concurrency settings to VEBA UI

files/getOvfProperty.py
Closes: #497
Verified fix through VEBA appliance build and deployment …
=> Replace is not with != as syntax is no longer valid for python 3.8+

http/photon-kickstart.json, photon-version.json, photon.json, scripts/photon-settings.sh
Closes: #493
* Verified successful build of VEBA appliance (build down reduced to 14min compared to 30min+) and deployment across various processors
If you have any questions/comments, feel free to reach …
=> Upgrade to Photon OS 4.0 GA

files/setup.sh
Closes: #498
* Successfully built and deployed VEBA appliance to ensure variables are properly escaped using both complex and non-complex passwords for testing
=> Improve variable escapes using jq instead of python snippets

files/downloads/antrea/overlay.yaml, files/downloads/contour-delegation.yaml, files/downloads/knative-contour/overlay.yaml, files/downloads/local-provisioner/overlay.yaml, files/downloads/rabbitmq-operator/overlay.yaml, photon.json, scripts/photon-containers.sh
Closes: #505
* Successfully built and deployed VEBA appliance to ensure no change in setup behavior
=> Templatize YAML downloads using YTT

.github/workflows/router-lint.yml, vmware-event-router/.golangci.yml, vmware-event-router/internal/config/v1alpha1/metrics.go, vmware-event-router/internal/config/v1alpha1/processor.go, vmware-event-router/internal/metrics/server.go, vmware-event-router/internal/provider/vcenter/checkpoint.go, vmware-event-router/internal/provider/vcsim/vcsim.go, vmware-event-router/internal/provider/webhook/webhook.go
Update golangci-lint configuration to address warnings. Also update comments to make linter happy.
Closes: #511
* Any other details you wish …
=> Update golangci-lint config

.github/workflows/create-docker-dev-image.yml, .github/workflows/create-docker-prerelease.yml, .github/workflows/create-docker-release.yml, .github/workflows/router-integration-tests.yml, .github/workflows/router-lint.yml, .github/workflows/router-unit-tests.yml, .github/workflows/router-verify-build.yml, .github/workflows/router-verify-helm.yml
=> Update workflows to Go v1.16

.github/workflows/create-docker-dev-image.yml, .github/workflows/create-docker-prerelease.yml, .github/workflows/create-docker-release.yml, .github/workflows/verify-docker-login.yaml
- Add nightly Docker login verification action
- Update Docker actions with more streamlined login method
Closes: #518
* Any other details …
=> chore: Update Docker related actions

photon.json
Closes: #522
This change updates the default grub image with the VEBA logo and is displayed during the bootup process. Below is a screenshot of what this looks like:
* Successfully built and deployed VEBA appliance to ensure no regression
Thank you from the VEBA …
=> Replace grub splash screen with VEBA logo

veba-bom.json
Closes: #502
* Successfully built/tested VEBA appliance to ensure there are no regressions. 
=> Update Antrea to v1.2.0 to resolve deprecated k8s API resources

.github/workflows/verify-docker-login.yaml
=> Fix Docker credentials in action

files/setup-099-banner.sh
=> Update /etc/issue login banner

files/configs/event-router/templates/vmware-event-router-config-template.yaml, files/configs/event-router/templates/vmware-event-router-k8s-template.yaml, files/configs/ingress/templates/ingressroute-gateway-template.yaml, files/setup.sh, manual/photon.xml.template
Closes: #496
This change incorporates the new Webhook Event Provider and users can enable it by simply selecting the box as well as provide optional basic auth configurations:
Here is an example sending to the new `/webhook` endpoint:
```console
{
"Message":"Hi Michael"
}
-H "Content-Type: application/json" \
-H 'ce-specversion: 1.0' \
-H 'ce-id: 1234' \
-H 'ce-source: william.lam' \
-H 'ce-type: webhook-custom' \
-H 'ce-subject: Webhook' \
-u 'veba:V3b@' \
--local-port 8080 \
-X POST -k https://veba.primp-industries.local/webhook
```
Using `/events` endpoint, we can confirm the new webhook is functional after sending a proper CloudEvent payload:
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this …
=> Integrate Webhook Event Provider into VEBA

files/setup-03-network.sh
Closes: #532
* Verified that creating `/etc/cloud/cloud-init.disabled` file will preserve FQDN hostname upon reboot 
=> Disable cloud-init to preserve FQDN hostname upon reboot

files/setup.sh
Closes: #537
* Verified VEBA appliance behavior
=> Improve OVF debuggability

files/setup-010-veba-ui.sh
Closes: #538
* Verified VEBA appliance behavior
=> Prevent unexpected CLI argument quoting when using set -x

examples/knative/templates/server.ps1
Signed-off-by: Dimitar Milov <dmilov@vmware.com>
Update PowerShell server.ps1 to return 'Bad Request' response in case request is not a valid cloud event.
Fixes issue #459
Closes #459
- Ran server.ps1 locally
- …
=> PS server.ps1 return "Bad Request" on invalid cloud event

docs/_includes/site-header.html, docs/_layouts/timeline.html, docs/assets/_scss/_styles.scss, docs/assets/_scss/site/layouts/_timeline.scss, docs/assets/_scss/site/settings/_variables.scss, docs/site/evolutions.md
=> Adding VEBA Evolutions to the website

files/configs/event-router/templates/vmware-event-router-config-template.yaml, files/setup-098-dcui-endpoints.sh, files/setup.sh, manual/photon.xml.template
Closes: #526
This change incorporates the new Horizon Event Provider and users can enable it by simply selecting the box as well as the required paraemters:
```console
k get pods -A
NAMESPACE            NAME                                           READY   STATUS      RESTARTS   AGE
contour-external     contour-5869594b-76v6h                         1/1     Running     0          19m
contour-external     contour-5869594b-mxrm8                         1/1     Running     0          19m
contour-external     contour-certgen-v1.10.0-6wdmt                  0/1     Completed   0          19m
contour-external     envoy-2f4pg                                    2/2     Running     0          19m
contour-internal     contour-5d47766fd8-cft5z …
```
=> Integrate Horizon Event Provider into VEBA

files/configs/ingress/templates/ingressroute-gateway-template.yaml
=> Add Horizon Ingress

examples/knative/powercli/kn-pcli-tag/Dockerfile, examples/knative/powercli/kn-pcli-tag/README.md, examples/knative/powercli/kn-pcli-tag/function.yaml, examples/knative/powershell/kn-ps-echo/Dockerfile, examples/knative/powershell/kn-ps-echo/README.md, examples/knative/powershell/kn-ps-echo/function.yaml, examples/knative/powershell/kn-ps-email/Dockerfile, examples/knative/powershell/kn-ps-email/README.md, examples/knative/powershell/kn-ps-email/function.yaml, examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile, examples/knative/powershell/kn-ps-slack-vsphere-alarm/README.md, examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml, examples/knative/powershell/kn-ps-slack/Dockerfile, examples/knative/powershell/kn-ps-slack/README.md, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/templates/Dockerfile.pcli, examples/knative/templates/Dockerfile.ps, examples/knative/templates/README.md
Closes: #549
* Verified PS fixes
* Successfully built and pushed all PS/PCLI images to VMware Harbor registry
=> Apply server.ps1 fixes to all PS/CLI container images

docs/kb/advanced-certificates.md
=> Fix advanced docs cert section

manual/photon.xml.template
=> Update OVF labels with deprecated event processors

files/configs/fluentbit/templates/fluentbit-configmap-template.yaml, files/downloads/fluentbit/overlay.yaml, files/setup-011-fluentbit.sh
Closes: #572
* Successfully built VEBA OVA and was verified by @rguske that syslog configurations are now being processed and updated in fluentbig config map and logging is now being forward externally
=> Update Fluentbit config using YTT overlay

examples/knative/powercli/kn-pcli-tag/handler.ps1
=> Correct execption message for TAG_SECRET not being defined

docs/_config.yml, docs/index.html
This PR will add a new section to the website (Home) which highlights the two supported deployment methods for VEBA.
Closes: #517
* Successfully verified website adjustments locally
N/A
=> Add deployment methods section to welcome page

files/configs/knative/rabbit.yaml
If no retries are defined (globally on broker or per trigger), the current version of the rabbit broker used in VEBA keeps requeuing events in case of non-successful status code, causing almost infinite loops on functions.
This change temporarily fixes the behavior by setting a global retry policy on the broker with the following settings:
- two retries (i.e. 3 total invocations)
- linear backoff policy
Closes: #580
What …
=> fix: Set global retry policy on broker

files/setup.sh
Closes: #591
This fix prevents any strings that contain `$` character from being evaluated when `eval` command is running for escaped variables. Thanks to @embano1 for the tip!
=> Prevent $ char from being eval in escaped variables

README.md
=> Update Github Photon OS badge to 4.0

examples/knative/powercli/kn-pcli-tag/handler.ps1, examples/knative/powershell/kn-ps-echo/handler.ps1, examples/knative/powershell/kn-ps-email/handler.ps1, examples/knative/powershell/kn-ps-slack-vsphere-alarm/handler.ps1, examples/knative/powershell/kn-ps-slack/handler.ps1, examples/knative/templates/server.ps1
By adding `-ErrorAction Stop` to the appropriate lines of code in the `handler.ps1`, it will correctly stop the function in case of a failure caused by e.g. wrong parameters (user, password, etc.), during its execution.
Closes: #573
* Successfully tested the new handler(.ps1) adjustments by using the simulated vCenter event method (`Docker`) locally as well as with the kn-pcli-tag function itself
N/A
=> Fix the error stopping behaviour for kn-pcli-tag function

examples/knative/powercli/kn-pcli-tag/Dockerfile, examples/knative/powercli/kn-pcli-tag/function.yaml, examples/knative/powershell/kn-ps-echo/Dockerfile, examples/knative/powershell/kn-ps-echo/function.yaml, examples/knative/powershell/kn-ps-email/Dockerfile, examples/knative/powershell/kn-ps-email/function.yaml, examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile, examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml, examples/knative/powershell/kn-ps-slack/Dockerfile, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/templates/Dockerfile.pcli, examples/knative/templates/README.md
Closes: #594
Apply latest `server.ps1` fixes to all existing PS/PCLI container images and built/push new container images to VMware Harbor. CDN has also been warmed up with the new container images
=> Update PS/PCLI images with latest server.ps1 fixes

examples/knative/powershell/kn-ps-slack/handler.ps1
=> Update kn-ps-slack with try/catch

files/configs/fluentbit/templates/fluentbit-configmap-template.yaml, files/configs/fluentbit/templates/fluentbit-ds-template.yaml
Update the `INPUT` configuration for the `tail` plugin within the `ConfigMap` as well as the memory resource limit `spec` for the `DaemonSet`, to have enough memory in place to store the log data temporary.
Closes: #604
* Successfully tested the configuration changes
N/A
=> Update Fluent Bit configuration to fix mem buf overlimit

README.md, docs/_data/default.yml, docs/kb/intro-about.md, docs/kb/intro-architecture.md, docs/kb/intro-event-router.md, docs/kb/use-horizon-events.md, docs/kb/use-vcenter-events.md
Closes: #596
This change updates the various description and pages to incorporate the newly supported Event Providers
**Note:** I will update the VEBA Fling description once this PR has been merged
=> Updated description for VEBA in Docs

docs/kb/install-eventbridge.md, docs/kb/install-knative.md, docs/kb/install-openfaas.md
=> Updated VEBA Appliance deployment guides

docs/kb/contribute-start.md
=> Updated Getting Started Guide w/Knative

.github/workflows/create-docker-dev-image.yml, .github/workflows/create-docker-prerelease.yml, .github/workflows/create-docker-release.yml, .github/workflows/router-integration-tests.yml, .github/workflows/router-lint.yml, .github/workflows/router-unit-tests.yml, .github/workflows/router-verify-build.yml, .github/workflows/router-verify-helm.yml, vmware-event-router/Dockerfile, vmware-event-router/internal/events/events_test.go, vmware-event-router/internal/integration/events_test.go, vmware-event-router/internal/processor/openfaas/openfaas_test.go, vmware-event-router/internal/processor/openfaas/retry_test.go, vmware-event-router/internal/processor/processor_test.go, vmware-event-router/internal/provider/fake/vcenter_fake_test.go, vmware-event-router/internal/provider/horizon/client_internal_test.go, vmware-event-router/internal/provider/horizon/horizon_internal_test.go, vmware-event-router/internal/provider/horizon/horizon_test.go, vmware-event-router/internal/provider/vcenter/checkpoint_test.go, vmware-event-router/internal/provider/vcenter/vcenter_test.go, vmware-event-router/internal/provider/vcsim/vcsim_test.go, vmware-event-router/internal/provider/webhook/webhook_internal_test.go, vmware-event-router/internal/provider/webhook/webhook_test.go, vmware-event-router/internal/util/util_test.go
Bump 
- build chain to Go v1.7
- Docker images to latest versions (Go, Ubuntu)
Fix build related changes (linter complaining about old build tag style)
Closes: #616
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by …
=> chore: Bump Event Router build versions

examples/knative/templates/server.ps1
=> fix: Formatting in server.ps1

docs/site/evolutions.md
=> Updated VEBA timeline with v0.7 release

examples/knative/powershell/kn-ps-slack/handler.ps1
Adds full message to the kn-ps-slack payload, makes pretext generic.
The function is currently designed to handle the VM Powered Off event. This change makes it more generic by removing the PoweredOff-specific language in the pretext, and adding FullFormattedMessage to the payload. This will let the user configure any subject in function.yaml without having to change the handler.
- [x ] Feature (non-breaking change which adds functionality)
* Short summary of …
=> Convert kn-ps-slack function to handle all events

docs/README.md, docs/kb/contribute-site.md
=> Simplify docs testing/contribution using Jekyll Docker image

examples/knative/powercli/kn-pcli-tag/Dockerfile, examples/knative/powercli/kn-pcli-tag/function.yaml, examples/knative/powercli/kn-pcli-telegram/Dockerfile, examples/knative/powercli/kn-pcli-telegram/function.yaml, examples/knative/powershell/kn-ps-echo/Dockerfile, examples/knative/powershell/kn-ps-echo/function.yaml, examples/knative/powershell/kn-ps-email/Dockerfile, examples/knative/powershell/kn-ps-email/function.yaml, examples/knative/powershell/kn-ps-horizon-login-slack/Dockerfile, examples/knative/powershell/kn-ps-horizon-login-slack/function.yaml, examples/knative/powershell/kn-ps-ngw-slack/Dockerfile, examples/knative/powershell/kn-ps-ngw-slack/function.yaml, examples/knative/powershell/kn-ps-ngw-teams/Dockerfile, examples/knative/powershell/kn-ps-ngw-teams/function.yaml, examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile, examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml, examples/knative/powershell/kn-ps-slack/Dockerfile, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/powershell/kn-ps-twillio-sms/Dockerfile, examples/knative/powershell/kn-ps-twillio-sms/function.yaml, examples/knative/powershell/kn-ps-webhook/Dockerfile, examples/knative/powershell/kn-ps-webhook/function.yaml, examples/knative/powershell/kn-ps-webhook/server.ps1, examples/knative/templates/Dockerfile.pcli, examples/knative/templates/Dockerfile.ps, examples/knative/templates/README.md
Closes: #595
* Updated PowerShell + CE SDK Version
* Updated PowerCLI Version
* Updated all PS/PCLI Images with new base image versions
* Incorporated latest server.ps1 into PS Webhook Function
=> Update PS/PCLI images w/latest CE SDK/PowerCLI versions

files/setup-06-event-processor.sh
=> fix: Prevent duplicate Processor entries in /etc/veba-release

scripts/photon-settings.sh
Closes: #640
Fix to ensure `conntrackd` service properly starts up. This is a temp fix until Photon OS team incorporates the correct configuration file for Photon OS 4.0.
Verified new build w/workaround
=> Update conntrackd config to run properly in Photon OS 4.0

examples/knative/go/kn-go-echo/function.yaml, examples/knative/powercli/kn-pcli-snapshot-cron/Dockerfile, examples/knative/powercli/kn-pcli-snapshot-cron/function.yaml, examples/knative/powercli/kn-pcli-tag/Dockerfile, examples/knative/powercli/kn-pcli-tag/function.yaml, examples/knative/powercli/kn-pcli-telegram/Dockerfile, examples/knative/powercli/kn-pcli-telegram/function.yaml, examples/knative/powershell/kn-ps-echo/Dockerfile, examples/knative/powershell/kn-ps-echo/function.yaml, examples/knative/powershell/kn-ps-email/Dockerfile, examples/knative/powershell/kn-ps-email/function.yaml, examples/knative/powershell/kn-ps-horizon-login-slack/Dockerfile, examples/knative/powershell/kn-ps-horizon-login-slack/function.yaml, examples/knative/powershell/kn-ps-ngw-slack/Dockerfile, examples/knative/powershell/kn-ps-ngw-slack/function.yaml, examples/knative/powershell/kn-ps-ngw-teams/Dockerfile, examples/knative/powershell/kn-ps-ngw-teams/function.yaml, examples/knative/powershell/kn-ps-slack-vsphere-alarm/Dockerfile, examples/knative/powershell/kn-ps-slack-vsphere-alarm/function.yaml, examples/knative/powershell/kn-ps-slack/Dockerfile, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/powershell/kn-ps-twillio-sms/Dockerfile, examples/knative/powershell/kn-ps-twillio-sms/function.yaml, examples/knative/powershell/kn-ps-webhook/Dockerfile, examples/knative/powershell/kn-ps-webhook/function.yaml, examples/knative/python/kn-py-echo/function.yaml, examples/knative/python/kn-py-slack/function.yaml, examples/knative/python/kn-py-vm-attr/function.yaml, examples/knative/templates/Dockerfile.pcli, examples/knative/templates/README.md
Migrate Knative function examples to `us.gcr.io`.
Closes: #644
Deployed Slack example against v0.7.0-pre-release by @lamw 
If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/arc …
=> Migrate Knative examples to us.gcr.io

README.md
Changes:
- Formatting README with line-wrap
- Added community calls section
Closes: #649
* Short …
=> chore: Add note on community calls

examples/knative/powercli/kn-pcli-nsx-tag-sync/README.md
=> docs: Fix variable rendering in PCLI tag sync

test/deploy_veba_knative_processor.sh, test/deploy_veba_knative_processor_veba_ui.sh, test/deploy_veba_knative_processor_veba_ui_webhook.sh
Closes: #714
This change simply adds a few examples for deploying VEBA OVA using Knative processor. It includes standard Knative deployment, Knative + VEBA UI and Knative + VEBA UI + Webhook example
=> Add VEBA OVA deployment scripts for Knative

photon.json
Closes: #718
Reference the new v2 VEBA logo for splash screen used within OS bootup
=> Update VEBA logo in packer build to v2

docs/assets/_scss/bootstrap-4.1.3/_variables.scss, docs/assets/_scss/site/layouts/_documentation.scss, docs/kb/intro-event-router.md, vmware-event-router/README.MD
Closes Issue with website Header UI rendering. 
* Website tested locally. Additionally, here is the screenshot for how the …
=> Updating style for headers and TOC for Event Router page

docs/kb/contribute-site.md, docs/site/examples-knative.md
Signed-off-by: David Bibby <davidsbibby@gmail.com>
Closes #730 
Closes #734 
* Successfully built and tested website locally.
* Note: cannot test links to new functions …
=> Add new functions to website

test/deploy_veba_knative_processor.sh, test/deploy_veba_knative_processor_veba_ui.sh, test/deploy_veba_knative_processor_veba_ui_webhook.sh
- [ X] Documentation changes
Deployed VEBA appliance on Windows using the instructions
If you have any …
=> Add Windows instructions to OVA deployment scripts

docs/site/evolutions.md
=> Add v0.7.1 release to VEBA timeline

docs/site/evolutions.md
=> Minor update to the VEBA timeline for v0.7.1 release

examples/knative/powershell/kn-ps-slack-vsphere-alarm/README.md
Update Alarms function example docs
Closes #750 …
=> docs: Update Alarms Example

examples/knative/go/kn-go-tagging/main_test.go, examples/knative/go/kn-go-tagging/tagging/tagging_test.go
=> fix: Go tests in kn-go-tagging

docs/kb/install-knative.md, docs/site/examples.md, files/configs/event-router/templates/vmware-event-router-config-template.yaml, files/configs/ingress/templates/ingressroute-gateway-template.yaml, files/setup-01-os.sh, files/setup-04-kubernetes.sh, files/setup-06-event-processor.sh, files/setup-09-ingress.sh, files/setup-098-dcui-endpoints.sh, files/setup.sh, manual/photon.xml.template
=> Remove support for External Knative Processor

docs/_includes/contributors.html
[Signed-off-by:] Patrick Kremer <pkremer@vmware.com>
Updated contributors list as follows:
- Removes old Otto logo
- Suppresses dependabot
- Reconfigures div to completely skip suppressed contributors instead of leaving an empty space in the thumbnail grid
- [X ] Documentation changes
Tested locally with Jekyll docker image
* OId …
=> docs: Hide bot contributors, remove Otto

veba-bom.json, vmware-event-router/hack/run_integration_tests.sh
=> Update K8s to v1.21.5

docs/README.md, docs/kb/contribute-site.md
Added Windows instructions to the website - previously they only existed in the README.
Added --force-polling workaround to Windows instructions
Closes #761 
Built locally, tested in browser.
=> Add Windows instructions for Jekyll to website and README

files/configs/event-router/vmware-event-router-clusterrole.yaml, files/configs/knative/rabbit.yaml, files/downloads/cert-manager/overlay.yaml, files/downloads/rabbitmq-messaging-operator/overlay.yaml, files/setup-05-knative.sh, scripts/photon-containers.sh, scripts/photon-settings.sh, veba-bom.json
=> Update Knative Serving/Eventing stack to v1.1.0

test/deploy_veba_knative_processor.sh, test/deploy_veba_knative_processor_veba_ui.sh
=> Remove Docker CIDR & Processor Type from VEBA deployment script

docs/kb/advanced-certificates.md
Closes #759
Executed instructions against VEBA 0.7.1 appliance.
Viewed website changes locally using Jekyll.
=> Add Let's Encrypt documentation to Advanced Certificates section

docs/kb/advanced-certificates.md, docs/kb/troubleshoot-appliance.md
The guide references /root/config/event-router-config.yaml, but the file has moved to /root/config/event-router/vmware-event-router-config-vcenter.yaml - advanced certificates and appliance troubleshooting sections.
- [ x] Documentation changes
Closes #764 
Built Jekyll locally, brought up changes in web browser
If you have any …
=> docs: Update event router config path

.github/workflows/check-wip-pr.yml, .github/workflows/gcr-dev-image.yml, .github/workflows/gcr-prerelease-image.yml, .github/workflows/issue-greeting.yml, .github/workflows/release.yml, .github/workflows/router-build.yml, .github/workflows/router-helm.yml, .github/workflows/router-integration-tests.yml, .github/workflows/router-lint.yml, .github/workflows/router-unit-tests.yml, .github/workflows/stale.yml, .github/workflows/verify-gcr-login.yaml
Closes: #780
Use fully-qualified SHA256 commit IDs in workflows.
Closes #780
Tested with a fake commit triggering most of the pipelines (cron jobs/releases won't run but should work as expected). …
=> Use SHA IDs in Github workflows

.github/workflows/router-helm.yml
=> Sync Knative version in Github Actions with BOM

examples/knative/powershell/kn-ps-slack/README.md, examples/knative/powershell/kn-ps-slack/function.yaml, examples/knative/powershell/kn-ps-slack/handler.ps1, examples/knative/powershell/kn-ps-slack/slack_secret.json, examples/knative/powershell/kn-ps-slack/test/docker-test-env-variable
Closes: #785
Closes: #784 
The function is now Event agnostic and includes the `EventType` within the Slack Message as well as allowing users to customize the pretext which is displayed at the top of the Slack Notification (see screenshot below)
=> Slack Function enhancement: event agnostic + customized message

photon-version.json, scripts/photon-settings.sh
Closes: #788
Update to latest Photon OS release (4.0 Rev 2) and ensure successful build of VEBA Appliance
=> Update to Photon OS 4.0 Rev2

README.md
=> docs: Add Zoom password note

files/setup-011-fluentbit.sh, files/setup-012-cadvisor.sh, files/setup-05-knative.sh, files/setup-07-event-router.sh, files/setup.sh
Increases kubectl timeout to 10 minutes
Closes #792 
=> feat: Increase kubectl wait time

files/configs/knative/templates/rabbit-template.yaml, files/setup-05-knative.sh, veba-bom.json
Closes: #795
RabbitMQ image was incorrectly removed from BOM, which causes the image to be pulled from internet, which breaks air-gap requirements. This resolves the original issue and also specifies the explicit version of RabbitMQ version in deployment spec
=> Ensure RabbitMQ image is pre-pulled

veba-bom.json
Closes: #800
k8s deployment requires BOTH pause container version `3.4.1` and `3.5` (which was missing) which breaks air-gap deployment
=> Add pause container 3.5

files/downloads/knative-contour/overlay.yaml
Closes: #803
This change updates Envoy to listen to ports 80/443 which is required to access VEBA endpoints
=> Update Envoy to listen on 80/443

examples/knative/powercli/kn-pcli-template/README.md, examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.ps1, examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.sh
Closes #807
Enables an optional argument in the /test scripts. Default with no argument behaves the same as the previous version, using `test-payload.json` as the filename.
If an argument is passed, the script will verify the passed filename exists, and if so send it as the payload.
Closes #807 
Tested on Windows pwsh 7.1.4 and Git …
=> feat: Test scripts accept payload filename argument

examples/knative/powercli/kn-pcli-template/README.md, examples/knative/powercli/kn-pcli-template/function.yaml, examples/knative/powercli/kn-pcli-template/handler.ps1
Closes #810
* Please include any relevant …
=> docs: Clarified naming a new function

docs/site/evolutions.md
Closes: #814
Update VEBA Evolution website page for v0.7.2 release
=> Update VEBA Evolution page w/v0.7.2 release

examples/knative/powercli/kn-pcli-nsx-tag-sync/function.yaml, examples/knative/powercli/kn-pcli-nsx-tag-sync/handler.ps1
=> fix: NSX tag sync DEBUG statements

docs/_data/default.yml, docs/kb/private-registry.md
=> Instructions for using private container registry

docs/_data/default.yml
=> Open private container registry doc in same window

docs/kb/intro-about.md, docs/kb/intro-functions.md
Closes #820
Updates bad links on website
Closes #820 
Built locally with Jekyll, tested in local browser.
=> docs: Update bad links in functions pages

examples/knative/powercli/kn-pcli-nsx-tag-sync/README.md, examples/knative/powercli/kn-pcli-nsx-tag-sync/function.yaml, examples/knative/powercli/kn-pcli-nsx-tag-sync/handler.ps1
Closes #834
- Handle unicode characters in tag names by encoding the payload as utf-8
- Gracefully handle errors when a non-VM object gets tagged
Tested against VEBA 0.7.0
=> fix: Handle unicode characters in tag names

vmware-event-router/deploy/event-router-config-vcenter-aws-iam-role-auth.yaml, vmware-event-router/internal/config/v1alpha1/auth.go, vmware-event-router/internal/config/v1alpha1/processor.go, vmware-event-router/internal/processor/aws/aws_event_bridge.go
- [] Please include any relevant screenshots and/or output as part of your testing
Closes #823
* Short summary of testing (e.g. successfully built and deployed VMware …
=> feat: Add iam_auth_role for EventBridge

docs/kb/troubleshoot-appliance.md
Closes #854
Adds troubleshooting topics on verifying that the install completed succesfully and where install logs are located.
Tested locally with Jekyll
=> docs: Expand troubleshooting guide

examples/knative/powercli/kn-pcli-template/README.md, examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.ps1, examples/knative/powercli/kn-pcli-template/test/send-cloudevent-test.sh
Closes #858
This feature adds the ability to pass an event subject as an argument to the function testing scripts. This allows for easy testing in situations where you have multiple events and multiple payload files.
Tested on VEBA 0.7.0
=> Add optional event subject arg to testing scripts

docs/site/examples.md
Closes #862
Add the kn-pcli-hostmaint-alarms function from #856 to the website.
Tested locally with Jekyll
=> Add kn-pcli-hostmaint-alarms to website

examples/knative/powercli/kn-pcli-pg-check/function.yaml
Closes #878
Changes container reference from Docker to Google 
Closes #878
=> Update container image link for kn-pcli-pg-check

docs/kb/advanced-certificates.md
Closes #882
Adds start and stop instructions for the Docker daemon, which is default disabled now that VEBA uses containerd.
Closes #882
Verified locally with Jekyll
=> Add Docker daemon start/stop instructions to Let's Encrypt section

examples/knative/powershell/kn-ps-slack-vsphere-alarm/README.md, examples/knative/powershell/kn-ps-slack-vsphere-alarm/in-memory-channel.yaml
Closes: #886
Signed-off-by: David Bibby <david.bibby@dxc.com>
On investigating #886 I found the image references in the current `in-memory-channel.yamnl` are all now invalid - looks like the knative gcr.io registry paths have all changed at some point.
Tried updating the `in-memory-channel.yaml` file to one based on the [knative/eventing release v1.1.0](https://github.com/knative/eventing/releases/tag/knative-v1.1.0) (chosen to match the VEBA BOM knative eventing version) and this seem to resolve the issue.
Also found a minor docs issue in the README.md
Please …
=> fix: update in-memory-channel.yaml to knative/eventing v1.1.0 release

build.sh, docs/kb/contribute-appliance.md
Small documentation updates to address recent changes to the size of the appliance.
Small improvement suggested to the `build.sh` script.
Closes #841 
* Built appliance …
=> docs: Update appliance build documentation

examples/knative/python/kn-py-echo/requirements.txt, examples/knative/python/kn-py-slack/handler.py, examples/knative/python/kn-py-slack/requirements.txt, examples/knative/python/kn-py-vm-attr/requirements.txt, examples/knative/python/kn-py-vro/requirements.txt
Signed-off-by: David Bibby <davidsbibby@gmail.com>
Fixes #806 by updating the Flask version to v2.1.2
Additionally all requirements.txt files are now hard locked - all dependencies are listed with fixed versions.
Closes #806
* Each Python example function has been built locally and tested fully to confirm functionality.
If you have …
=> fix: Resolved issues with old Flask versions

examples/knative/python/kn-py-echo/README.md, examples/knative/python/kn-py-echo/function.yaml, examples/knative/python/kn-py-slack/README.md, examples/knative/python/kn-py-slack/function.yaml, examples/knative/python/kn-py-slack/requirements.txt, examples/knative/python/kn-py-vm-attr/function.yaml, examples/knative/python/kn-py-vro/README.md, examples/knative/python/kn-py-vro/function.yaml
Updated Python images and pushed to `gcr.io`
If you have any questions/comments, feel …
=> chore: Update Python examples

docs/_functions/sample1.md, docs/_functions/sample3.md, docs/kb/deploy-event-router-kind.md, docs/kb/function-tutorial-intro.md, docs/kb/intro-event-router.md, docs/site/community.md, vmware-event-router/README.MD
Update documentation to fix broken links and always reference to `master` branch. Also add section on commit naming and PR creation in CONTRIB guide.
* Any other details you wish to include …
=> docs: Update documentation

docs/site/faq.md
Adjust the link for the Event-Router in FAQ 3 so it is pointing to the Event-Router page itself instead of [Contribute](https://vmweventbroker.io/kb/contribute-eventrouter). 
Update the link reference in FAQ 6 due to the recently added section for the use of Private Registries.
Closes: #899
* Verified changes made locally first
=> docs: Update FAQs 3 and 6 on VEBA website

docs/kb/intro-event-router.md, vmware-event-router/README.MD
Adds the following link for Dead Letter Queue in the Event Router section.
https://en.wikipedia.org/wiki/Dead_letter_queue
Closes: #901
* Tested adjustments locally
=> docs: Adds a link to the explanation of the term Dead Letter Queue

docs/kb/use-vcenter-events.md
PR will update the [vCenter Events](https://vmweventbroker.io/kb/vcenter-events) page. More specifically, it'll update the link to the vSphere API reference as well as the number of available events to be vSphere 7 U3 comliant.
Closes: #903
* Tested changes locally
=> docs: Update vCenter Events page with vSphere U3 references and data

docs/site/examples.md, examples/knative/powershell/kn-ps-harbor-slack/Dockerfile, examples/knative/powershell/kn-ps-harbor-slack/README.md, examples/knative/powershell/kn-ps-harbor-slack/function.yaml, examples/knative/powershell/kn-ps-harbor-slack/handler.ps1, examples/knative/powershell/kn-ps-harbor-slack/slack_secret.json, examples/knative/powershell/kn-ps-harbor-slack/test/docker-test-env-variable, examples/knative/powershell/kn-ps-harbor-slack/test/send-cloudevent-test.ps1, examples/knative/powershell/kn-ps-harbor-slack/test/send-cloudevent-test.sh, examples/knative/powershell/kn-ps-harbor-slack/test/test-payload.json
Add example Knative PowerShell function for sending to a Slack webhook when the Harbor webhook feature is configured to send repository events to the [kn-go-harbor-webhook function example](https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/knative/go/kn-go-harbor-webhook).
Depends on open PR #915 
Closes #916 
* Tested function build locally first
* Tested function against a fully working environment
* Harbor webhook configuration
* Slack message
=> Add kn-ps-harbor-slack function

veba-bom.json
Git repo tag is not used, changing to dummy.
Closes: #918
* Short summary of testing (e.g. …
=> chore: Update VEBA UI version

examples/knative/go/kn-go-harbor-webhook/README.md
=> Fix Harbor example docs

docs/site/evolutions.md
This change adds upcoming `v0.7.3` release to VEBA Website
Closes #922 
* Verified locally via jekyl docker container that content is rendered as expected
N/A
=> Add v0.7.3 release to VEBA website

docs/site/evolutions.md
=> docs: Update VEBA Evolution page w/v0.7.4 release

.github/workflows/release.yml
In case my account won't have maintainer privileges on this repo anymore, this would break the workflow.
Closes: #938
Signed-off-by: Michael Gasch <15986659+embano1@users.noreply.github.com>
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. …
=> chore: Remove embano1 from workflow attribute

files/configs/kubernetes/templates/kubeconfig-template.yaml, files/setup-04-kubernetes.sh, photon.json, scripts/photon-settings.sh, veba-bom.json
Changes in this PR includes the folowing:
* Bump k8s to v1.25.5
* Bump kind to v1.25.3 to match VEBA core k8s version
* Bump Containerd to v1.6.15
* Bump Antrea to v1.10 (for latest CNI version)
* Appliance build issues (use Thin provisioning)
* Include package Apparmor-parser needed for latest k8s
Closes #985
Closes #986  
* Successfully …
=> feat: Bump k8s version to v1.25.5

veba-bom.json
This change adds support for latest stable CSI storage provisioner v0.0.23
Closes #992 
* Successfully built and deployed VEBA and confirmed desired behavior
=> feat: Bump CSI local storage provisioner to v0.0.23

veba-bom.json
This change adds support for latest Fluent Bit v2.0.8
Closes #987 
* Successfully built and deploy VEBA appliance
=> feat: Bump Fluent Bit to v2.0.8

.github/workflows/verify-gcr-login.yaml
Closes: #1017
* Please include any relevant …
=> fix: Replace spaces with dash in Github Action Id

.github/workflows/gcr-dev-image.yml, .github/workflows/gcr-prerelease-image.yml, .github/workflows/release.yml, .github/workflows/verify-gcr-login.yaml
Closes: #1017
* Please include any relevant …
=> fix: Update Github Action id with valid string

docs/site/evolutions.md
Added v0.7.5 updates to VEBA Evolution Timeline on the website.
Closes: #1023
* Validated changes locally
=> docs: Added v0.7.5 updates to VEBA Evolution timeline

docs/_data/resources.yml
Updated websites Resource page with latest VEBA content.
Closes: #1006
* Tested Site adjustments locally
=> docs: Update Resource page with latest VEBA content

examples/knative/go/kn-go-echo/function.yaml, examples/knative/go/kn-go-echo/go.mod, examples/knative/go/kn-go-harbor-webhook/function.yaml, examples/knative/go/kn-go-nsx-tag-sync/function.yaml, examples/knative/go/kn-go-preemption/function.yaml, examples/knative/go/kn-go-tagging/function.yaml, examples/knative/python/kn-py-echo/README.md, examples/knative/python/kn-py-echo/function.yaml, examples/knative/python/kn-py-slack/README.md, examples/knative/python/kn-py-slack/function.yaml, examples/knative/python/kn-py-vm-attr/function.yaml, examples/knative/python/kn-py-vro/function.yaml
This change updates the container images for Python/Go examples
Closes #1035
=> Build updated container images for Python/Go Examples

.github/workflows/check-wip-pr.yml
Update WIP action to `v2` to solve escaping issue. …
=> Update WIP action to v2

examples/knative/python/kn-py-vm-attr/README.md
Paragraph "Deploy" had a missing closing ```
=> missing closing ```

examples/knative/templates/Dockerfile.pcli, examples/knative/templates/Dockerfile.ps, examples/knative/templates/README.md
This change replaces PowerShell base container image from using VMware Photon OS to Microsoft PowerShell container image, which also follows what the PowerCLI team is using for their container image. Not only does this resolve issue mentioned in #1067 but we also benefit from automated testing from PowerCLI team for any PowerShell/PowerCLI issues and have a single container source. 
Closes: #1067
* Verified PowerShell Slack function works and no longer throws any certificate issue
* Any other details you wish to …
=> fix: Update PowerShell base image to use Microsoft container image

examples/knative/templates/Dockerfile.pcli, examples/knative/templates/README.md
This change updates the PowerCLI base image to use latest PowerCLI 13.1 release and is based on [VMware's official PowerCLI Core Dockerfile](https://github.com/vmware/powerclicore) as a reference. The additional Python 3.7.9 dependency is due to new Image Builder cmdlets requirements
Closes #1069 
* Verified vSphere Tagging function w/o any regression …
=> feat: Update PowerCLI base image to latest 13.1

examples/CONTRIBUTING.md, examples/knative/templates/Dockerfile.pcli
This change uses the correct FROM image reference in PowerCLI template and fixes minor doc's in CONTRIBUTING guide as it create variables but never actually used in the documentation
Closes: #1106
* Any other …
=> Use correct FROM image in PowerCLI template

files/configs/horizon-source/templates/horizon-source-template.yml, files/configs/vsphere-source/templates/vsphere-source-template.yml
This change ensures the default payload encoding for Tanzu Sources is using JSON, which is also the same format as the Event Router
Closes: #1148
Successfully built and deployed VEBA appliance and deployed function to ensure JSON encoding was properly set …
=> fix: Default to JSON payload encoding for Tanzu Sources

examples/knative/powercli/kn-pcli-nsx-tag-sync/function.yaml
This changes applies the correct filter for Tanzu Sources `type` versus `subject`
Closes: #1096
If you have any questions/comments, feel free to reach out to …
=> fix: Update Tag Attach/Detach func to type filter

README.md, vmware-event-router/README.MD
PR will update the main README file according to changes which are going to be introduced in v0.8. Furthermore, deprecation information will be added to Event Router README.
Closes: #1133
* Verified locally
=> Update README file according to VEBA v0.8 changes

README.md
PR will fix a wrong md formatting in the README file.
Closes: #1160
=> Fix wrong md formatting in README

docs/site/evolutions.md, scripts/photon-settings.sh, veba-bom.json
This PR will almost push every in the veba-bom.json listed component of VEBAs architecture to a higher version. This includes components like Kubernetes, Knative, Antrea, Cert-Manager, Contour, etc.
Version updates.
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed …
=> update all veba core-components to a higher version

scripts/photon-settings.sh
Adjusted `kn-vsphere` download section in `photon-settings.sh`. 
List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes 
Closes: #1165
* Validated the change by executing all adjusted commands manually
=> Update kn-vsphere binary download

files/setup-05-knative.sh
This change re-orders the Knative setup script based on the Knative's E2E CI/CD testing
Closes: #1169
* Manually built VEBA appliance and ensure it deployed w/o any regressions …
=> feat: Re-order Knative deployment based on Knative E2E testing

files/setup-07-event-router-webhook.sh, scripts/photon-settings.sh
This change ensures `/etc/veba-release` contains `Processor` entry due to backwards compat of VEBA DCUI
Closes: #1172
If you have any questions/comments, feel …
=> fix: Update /etc/veba-release to include Knative processor entry
